export type DeclarationType = 'GTGT' | 'TNDN' | 'TNCN'

export interface IndicatorRow {
  isHeader?: false
  code: string
  name: string
}
export interface HeaderRow {
  isHeader: true
  name: string
}
export type UiRow = IndicatorRow | HeaderRow

export const UI_CONFIG: Record<DeclarationType, UiRow[]> = {
  GTGT: [
    { isHeader: true, name: 'A. CÁC CHỈ TIÊU ĐẦU KỲ VÀ MUA VÀO' },
    { code: '21', name: 'Không phát sinh hoạt động mua, bán trong kỳ' },
    { code: '22', name: 'Thuế giá trị gia tăng còn được khấu trừ kỳ trước chuyển sang' },
    { code: '23', name: 'Giá trị hàng hóa, dịch vụ mua vào' },
    { code: '24', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ mua vào' },
    { code: '23a', name: 'Giá trị hàng hóa, dịch vụ nhập khẩu' },
    { code: '24a', name: 'Thuế giá trị gia tăng hàng hóa, dịch vụ nhập khẩu' },
    { code: '25', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ mua vào được khấu trừ kỳ này' },
    { isHeader: true, name: 'B. CÁC CHỈ TIÊU BÁN RA' },
    { code: '26', name: 'Giá trị hàng hóa, dịch vụ bán ra không chịu thuế giá trị gia tăng' },
    { code: '27', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế giá trị gia tăng' },
    { code: '28', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra chịu thuế giá trị gia tăng' },
    { code: '29', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế suất 0%' },
    { code: '30', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế suất 5%' },
    { code: '31', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra chịu thuế suất 5%' },
    { code: '32', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế suất 10%' },
    { code: '33', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra chịu thuế suất 10%' },
    { code: '32a', name: 'Giá trị hàng hóa, dịch vụ bán ra không tính thuế' },
    { code: '34', name: 'Tổng doanh thu của hàng hóa, dịch vụ bán ra' },
    { code: '35', name: 'Tổng thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra' },
    { isHeader: true, name: 'C. XÁC ĐỊNH NGHĨA VỤ THUẾ' },
    { code: '36', name: 'Thuế giá trị gia tăng phát sinh trong kỳ' },
    { code: '37', name: 'Điều chỉnh giảm (thuế GTGT còn được khấu trừ của các kỳ trước)' },
    { code: '38', name: 'Điều chỉnh tăng (thuế GTGT còn được khấu trừ của các kỳ trước)' },
    { code: '39a', name: 'Thuế giá trị gia tăng nhận bàn giao được khấu trừ trong kỳ' },
    { code: '40a', name: 'Thuế giá trị gia tăng phải nộp của hoạt động sản xuất kinh doanh trong kỳ' },
    { code: '40b', name: 'Thuế giá trị gia tăng mua vào của dự án đầu tư được bù trừ với thuế GTGT còn phải nộp' },
    { code: '40', name: 'Thuế giá trị gia tăng còn phải nộp trong kỳ' },
    { code: '41', name: 'Thuế giá trị gia tăng chưa khấu trừ hết kỳ này' },
    { code: '42', name: 'Thuế giá trị gia tăng đề nghị hoàn' },
    { code: '43', name: 'Thuế giá trị gia tăng còn được khấu trừ chuyển kỳ sau' },
  ],
  TNDN: [
    { isHeader: true, name: 'KẾT QUẢ GHI NHẬN THEO BÁO CÁO TÀI CHÍNH' },
    { code: '04', name: '1. Doanh thu bán hàng và cung cấp dịch vụ' },
    { code: '05', name: 'Trong đó: - Doanh thu bán hàng hoá, dịch vụ xuất khẩu' },
    { code: '06', name: '2. Các khoản giảm trừ doanh thu' },
    { code: '07', name: 'a. Chiết khấu thương mại' },
    { code: '08', name: 'b. Giảm giá hàng bán' },
    { code: '09', name: 'c. Giá trị hàng bán bị trả lại' },
    { code: '10', name: '3. Doanh thu hoạt động tài chính' },
    { code: '11', name: 'Trong đó: Doanh thu từ lãi tiền gửi' },
    { code: '12', name: '4. Chi phí sản xuất, kinh doanh hàng hoá, dịch vụ' },
    { code: '13', name: 'a. Giá vốn hàng bán' },
    { code: '14', name: 'b. Chi phí bán hàng' },
    { code: '15', name: 'c. Chi phí quản lý doanh nghiệp' },
    { code: '16', name: '5. Chi phí tài chính' },
    { code: '17', name: 'Trong đó: Chi phí lãi tiền vay' },
    { code: '18', name: '6. Lợi nhuận thuần từ hoạt động kinh doanh' },
    { code: '19', name: '7. Thu nhập khác' },
    { code: '20', name: '8. Chi phí khác' },
    { code: '21', name: '9. Lợi nhuận khác' },
    { code: '22', name: '10. Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp' },
    { isHeader: true, name: 'A. KẾT QUẢ KINH DOANH GHI NHẬN THEO BÁO CÁO TÀI CHÍNH' },
    { code: 'A1', name: '1. Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp' },
    { isHeader: true, name: 'B. XÁC ĐỊNH THU NHẬP CHỊU THUẾ THEO LUẬT THUẾ TNDN' },
    { code: 'B1', name: '1. Điều chỉnh tăng tổng lợi nhuận trước thuế' },
    { code: 'B2', name: '1.1. Các khoản điều chỉnh tăng doanh thu' },
    { code: 'B3', name: '1.2. Chi phí của phần doanh thu điều chỉnh giảm' },
    { code: 'B4', name: '1.3. Các khoản chi không được trừ khi xác định thu nhập chịu thuế' },
    { code: 'B5', name: '1.4. Thuế thu nhập đã nộp cho phần thu nhập nhận được ở nước ngoài' },
    { code: 'B6', name: '1.5. Điều chỉnh tăng lợi nhuận do xác định giá thị trường' },
    { code: 'B7', name: '1.6. Các khoản điều chỉnh làm tăng lợi nhuận trước thuế khác' },
    { code: 'B8', name: '2. Điều chỉnh giảm tổng lợi nhuận trước thuế' },
    { code: 'B9', name: '2.1. Giảm trừ các khoản doanh thu đã tính thuế năm trước' },
    { code: 'B10', name: '2.2. Chi phí của phần doanh thu điều chỉnh tăng' },
    { code: 'B11', name: '2.3. Chi phí lãi vay không được trừ kỳ trước được chuyển sang kỳ này' },
    { code: 'B12', name: '2.4. Các khoản điều chỉnh làm giảm lợi nhuận trước thuế khác' },
    { code: 'B13', name: '3. Tổng thu nhập chịu thuế (B13 = A1 + B1 - B8)' },
    { code: 'B14', name: '3.1. Thu nhập chịu thuế từ hoạt động sản xuất kinh doanh' },
    { code: 'B15', name: '3.2. Thu nhập chịu thuế từ hoạt động chuyển nhượng bất động sản' },
    { isHeader: true, name: 'C. THUẾ TNDN PHẢI NỘP TỪ HOẠT ĐỘNG SXKD' },
    { code: 'C1', name: '1. Thu nhập chịu thuế (C1 = B14)' },
    { code: 'C2', name: '2. Thu nhập miễn thuế' },
    { code: 'C3', name: '3. Chuyển lỗ và bù trừ lãi, lỗ' },
    { code: 'C3a', name: '3.1. Lỗ từ hoạt động SXKD được chuyển trong kỳ' },
    { code: 'C3c', name: '3.2. Lỗ từ chuyển nhượng BĐS được bù trừ với lãi của SXKD' },
    { code: 'C4', name: '4. Thu nhập tính thuế (C4 = C1 - C2 - C3)' },
    { code: 'C5', name: '5. Trích lập quỹ khoa học công nghệ (nếu có)' },
    { code: 'C6', name: '6. TNTT sau khi đã trích lập quỹ KH&CN' },
    { code: 'C7', name: '6.1. Thu nhập tính thuế áp dụng thuế suất 15%' },
    { code: 'C8', name: '6.2. Thu nhập tính thuế tính theo thuế suất không ưu đãi khác' },
    { code: 'C8a', name: '6.3. Thuế suất không ưu đãi khác (%)' },
    { code: 'C9', name: '7. Thuế TNDN từ hoạt động SXKD tính theo thuế suất không ưu đãi' },
    { code: 'C10', name: '8. Thuế TNDN được ưu đãi theo Luật thuế TNDN' },
    { code: 'C11', name: '8.1. Thuế TNDN chênh lệch do áp dụng mức thuế suất ưu đãi' },
    { code: 'C12', name: '8.2. Thuế TNDN được miễn trong kỳ' },
    { code: 'C13', name: '8.3. Thuế TNDN được giảm trong kỳ' },
    { code: 'C14', name: '9. Thuế TNDN được miễn, giảm theo Hiệp định thuế' },
    { code: 'C15', name: '10. Thuế TNDN được miễn, giảm theo từng thời kỳ' },
    { code: 'C16', name: '11. Thuế thu nhập đã nộp ở nước ngoài được trừ trong kỳ tính thuế' },
    { code: 'C17', name: '12. Thuế TNDN phải nộp của hoạt động SXKD' },
    { isHeader: true, name: 'D. THUẾ TNDN PHẢI NỘP TỪ HOẠT ĐỘNG CHUYỂN NHƯỢNG BĐS' },
    { code: 'D1', name: '1. Thu nhập chịu thuế (D1 = B15)' },
    { code: 'D2', name: '2. Lỗ từ hoạt động chuyển nhượng BĐS được chuyển' },
    { code: 'D3', name: '3. Thu nhập tính thuế (D3 = D1 - D2)' },
    { code: 'D4', name: '4. Trích lập quỹ khoa học công nghệ (nếu có)' },
    { code: 'D5', name: '5. TNTT sau khi đã trích lập quỹ KH&CN' },
    { code: 'D6', name: '6. Thuế TNDN phải nộp từ chuyển nhượng BĐS (D6 = D5 x 22%)' },
    { code: 'D7', name: '7. Thuế TNDN được miễn, giảm' },
    { code: 'D8', name: '8. Thuế TNDN phải nộp sau miễn, giảm' },
    { isHeader: true, name: 'E. TỔNG THUẾ TNDN PHẢI NỘP TRONG KỲ' },
    { code: 'E1', name: '1. Tổng số thuế TNDN phải nộp' },
    { code: 'E2', name: '2. Thuế TNDN đã tạm nộp trong năm' },
    { code: 'E3', name: '3. Thuế TNDN còn phải nộp' },
    { code: 'E4', name: '4. Thuế TNDN nộp thừa' },
    { code: 'E5', name: '5. Thuế TNDN còn phải nộp sau khi bù trừ' },
    { code: 'E6', name: '6. Thuế TNDN nộp thừa sau khi bù trừ' },
  ],
  TNCN: [
    { isHeader: true, name: 'TỔNG HỢP THUẾ THU NHẬP CÁ NHÂN' },
    { code: '16', name: 'Tổng số người có thu nhập' },
    { code: '17', name: 'Trong đó: Số người thuộc diện phải nộp thuế' },
    { code: '18', name: 'Tổng thu nhập chịu thuế' },
    { code: '19', name: 'Tổng thu nhập tính thuế' },
    { code: '20', name: 'Tổng số thuế TNCN đã khấu trừ' },
    { code: '21', name: 'Tổng số thuế TNCN phải nộp' },
    { code: '22', name: 'Tổng số thuế TNCN đã nộp vào NSNN' },
    { code: '23', name: 'Tổng số thuế TNCN còn phải nộp' },
    { code: '24', name: 'Tổng số thuế TNCN nộp thừa' },
    { code: '25', name: 'Số người đề nghị quyết toán thay' },
    { code: '26', name: 'Số người có số thuế TNCN đề nghị hoàn trả' },
    { code: '27', name: 'Số tiền thuế TNCN đề nghị hoàn trả' },
    { code: '28', name: 'Số người có số thuế TNCN còn phải nộp' },
    { code: '29', name: 'Số thuế TNCN còn phải nộp' },
    { code: '30', name: 'Số người có số thuế TNCN bù trừ với số thuế nộp thừa' },
    { code: '31', name: 'Số thuế TNCN bù trừ với số thuế nộp thừa' },
    { code: '32', name: 'Số thuế TNCN còn phải nộp sau bù trừ' },
  ],
}
