export type DeclarationType = 'GTGT' | 'TNDN' | 'TNCN' | 'BCTC'

export interface IndicatorRow {
  isHeader?: false
  code: string
  name: string
}
export interface HeaderRow {
  isHeader: true
  name: string
}
export type UiRow = IndicatorRow | HeaderRow

export const UI_CONFIG: Record<DeclarationType, UiRow[]> = {
  GTGT: [
    { isHeader: true, name: 'A. CÁC CHỈ TIÊU ĐẦU KỲ VÀ MUA VÀO' },
    { code: '21', name: 'Không phát sinh hoạt động mua, bán trong kỳ' },
    { code: '22', name: 'Thuế giá trị gia tăng còn được khấu trừ kỳ trước chuyển sang' },
    { code: '23', name: 'Giá trị hàng hóa, dịch vụ mua vào' },
    { code: '24', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ mua vào' },
    { code: '23a', name: 'Giá trị hàng hóa, dịch vụ nhập khẩu' },
    { code: '24a', name: 'Thuế giá trị gia tăng hàng hóa, dịch vụ nhập khẩu' },
    { code: '25', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ mua vào được khấu trừ kỳ này' },
    { isHeader: true, name: 'B. CÁC CHỈ TIÊU BÁN RA' },
    { code: '26', name: 'Giá trị hàng hóa, dịch vụ bán ra không chịu thuế giá trị gia tăng' },
    { code: '27', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế giá trị gia tăng' },
    { code: '28', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra chịu thuế giá trị gia tăng' },
    { code: '29', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế suất 0%' },
    { code: '30', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế suất 5%' },
    { code: '31', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra chịu thuế suất 5%' },
    { code: '32', name: 'Giá trị hàng hóa, dịch vụ bán ra chịu thuế suất 10%' },
    { code: '33', name: 'Thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra chịu thuế suất 10%' },
    { code: '32a', name: 'Giá trị hàng hóa, dịch vụ bán ra không tính thuế' },
    { code: '34', name: 'Tổng doanh thu của hàng hóa, dịch vụ bán ra' },
    { code: '35', name: 'Tổng thuế giá trị gia tăng của hàng hóa, dịch vụ bán ra' },
    { isHeader: true, name: 'C. XÁC ĐỊNH NGHĨA VỤ THUẾ' },
    { code: '36', name: 'Thuế giá trị gia tăng phát sinh trong kỳ' },
    { code: '37', name: 'Điều chỉnh giảm (thuế GTGT còn được khấu trừ của các kỳ trước)' },
    { code: '38', name: 'Điều chỉnh tăng (thuế GTGT còn được khấu trừ của các kỳ trước)' },
    { code: '39a', name: 'Thuế giá trị gia tăng nhận bàn giao được khấu trừ trong kỳ' },
    { code: '40a', name: 'Thuế giá trị gia tăng phải nộp của hoạt động sản xuất kinh doanh trong kỳ' },
    { code: '40b', name: 'Thuế giá trị gia tăng mua vào của dự án đầu tư được bù trừ với thuế GTGT còn phải nộp' },
    { code: '40', name: 'Thuế giá trị gia tăng còn phải nộp trong kỳ' },
    { code: '41', name: 'Thuế giá trị gia tăng chưa khấu trừ hết kỳ này' },
    { code: '42', name: 'Thuế giá trị gia tăng đề nghị hoàn' },
    { code: '43', name: 'Thuế giá trị gia tăng còn được khấu trừ chuyển kỳ sau' },
  ],
  TNDN: [
    { isHeader: true, name: 'KẾT QUẢ GHI NHẬN THEO BÁO CÁO TÀI CHÍNH' },
    { code: '04', name: '1. Doanh thu bán hàng và cung cấp dịch vụ' },
    { code: '05', name: 'Trong đó: - Doanh thu bán hàng hoá, dịch vụ xuất khẩu' },
    { code: '06', name: '2. Các khoản giảm trừ doanh thu' },
    { code: '07', name: 'a. Chiết khấu thương mại' },
    { code: '08', name: 'b. Giảm giá hàng bán' },
    { code: '09', name: 'c. Giá trị hàng bán bị trả lại' },
    { code: '10', name: '3. Doanh thu hoạt động tài chính' },
    { code: '11', name: 'Trong đó: Doanh thu từ lãi tiền gửi' },
    { code: '12', name: '4. Chi phí sản xuất, kinh doanh hàng hoá, dịch vụ' },
    { code: '13', name: 'a. Giá vốn hàng bán' },
    { code: '14', name: 'b. Chi phí bán hàng' },
    { code: '15', name: 'c. Chi phí quản lý doanh nghiệp' },
    { code: '16', name: '5. Chi phí tài chính' },
    { code: '17', name: 'Trong đó: Chi phí lãi tiền vay' },
    { code: '18', name: '6. Lợi nhuận thuần từ hoạt động kinh doanh' },
    { code: '19', name: '7. Thu nhập khác' },
    { code: '20', name: '8. Chi phí khác' },
    { code: '21', name: '9. Lợi nhuận khác' },
    { code: '22', name: '10. Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp' },
    { isHeader: true, name: 'A. KẾT QUẢ KINH DOANH GHI NHẬN THEO BÁO CÁO TÀI CHÍNH' },
    { code: 'A1', name: '1. Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp' },
    { isHeader: true, name: 'B. XÁC ĐỊNH THU NHẬP CHỊU THUẾ THEO LUẬT THUẾ TNDN' },
    { code: 'B1', name: '1. Điều chỉnh tăng tổng lợi nhuận trước thuế' },
    { code: 'B2', name: '1.1. Các khoản điều chỉnh tăng doanh thu' },
    { code: 'B3', name: '1.2. Chi phí của phần doanh thu điều chỉnh giảm' },
    { code: 'B4', name: '1.3. Các khoản chi không được trừ khi xác định thu nhập chịu thuế' },
    { code: 'B5', name: '1.4. Thuế thu nhập đã nộp cho phần thu nhập nhận được ở nước ngoài' },
    { code: 'B6', name: '1.5. Điều chỉnh tăng lợi nhuận do xác định giá thị trường' },
    { code: 'B7', name: '1.6. Các khoản điều chỉnh làm tăng lợi nhuận trước thuế khác' },
    { code: 'B8', name: '2. Điều chỉnh giảm tổng lợi nhuận trước thuế' },
    { code: 'B9', name: '2.1. Giảm trừ các khoản doanh thu đã tính thuế năm trước' },
    { code: 'B10', name: '2.2. Chi phí của phần doanh thu điều chỉnh tăng' },
    { code: 'B11', name: '2.3. Chi phí lãi vay không được trừ kỳ trước được chuyển sang kỳ này' },
    { code: 'B12', name: '2.4. Các khoản điều chỉnh làm giảm lợi nhuận trước thuế khác' },
    { code: 'B13', name: '3. Tổng thu nhập chịu thuế (B13 = A1 + B1 - B8)' },
    { code: 'B14', name: '3.1. Thu nhập chịu thuế từ hoạt động sản xuất kinh doanh' },
    { code: 'B15', name: '3.2. Thu nhập chịu thuế từ hoạt động chuyển nhượng bất động sản' },
    { isHeader: true, name: 'C. THUẾ TNDN PHẢI NỘP TỪ HOẠT ĐỘNG SXKD' },
    { code: 'C1', name: '1. Thu nhập chịu thuế (C1 = B14)' },
    { code: 'C2', name: '2. Thu nhập miễn thuế' },
    { code: 'C3', name: '3. Chuyển lỗ và bù trừ lãi, lỗ' },
    { code: 'C3a', name: '3.1. Lỗ từ hoạt động SXKD được chuyển trong kỳ' },
    { code: 'C3c', name: '3.2. Lỗ từ chuyển nhượng BĐS được bù trừ với lãi của SXKD' },
    { code: 'C4', name: '4. Thu nhập tính thuế (C4 = C1 - C2 - C3)' },
    { code: 'C5', name: '5. Trích lập quỹ khoa học công nghệ (nếu có)' },
    { code: 'C6', name: '6. TNTT sau khi đã trích lập quỹ KH&CN' },
    { code: 'C7', name: '6.1. Thu nhập tính thuế áp dụng thuế suất 15%' },
    { code: 'C8', name: '6.2. Thu nhập tính thuế tính theo thuế suất không ưu đãi khác' },
    { code: 'C8a', name: '6.3. Thuế suất không ưu đãi khác (%)' },
    { code: 'C9', name: '7. Thuế TNDN từ hoạt động SXKD tính theo thuế suất không ưu đãi' },
    { code: 'C10', name: '8. Thuế TNDN được ưu đãi theo Luật thuế TNDN' },
    { code: 'C11', name: '8.1. Thuế TNDN chênh lệch do áp dụng mức thuế suất ưu đãi' },
    { code: 'C12', name: '8.2. Thuế TNDN được miễn trong kỳ' },
    { code: 'C13', name: '8.3. Thuế TNDN được giảm trong kỳ' },
    { code: 'C14', name: '9. Thuế TNDN được miễn, giảm theo Hiệp định thuế' },
    { code: 'C15', name: '10. Thuế TNDN được miễn, giảm theo từng thời kỳ' },
    { code: 'C16', name: '11. Thuế thu nhập đã nộp ở nước ngoài được trừ trong kỳ tính thuế' },
    { code: 'C17', name: '12. Thuế TNDN phải nộp của hoạt động SXKD' },
    { isHeader: true, name: 'D. THUẾ TNDN PHẢI NỘP TỪ HOẠT ĐỘNG CHUYỂN NHƯỢNG BĐS' },
    { code: 'D1', name: '1. Thu nhập chịu thuế (D1 = B15)' },
    { code: 'D2', name: '2. Lỗ từ hoạt động chuyển nhượng BĐS được chuyển' },
    { code: 'D3', name: '3. Thu nhập tính thuế (D3 = D1 - D2)' },
    { code: 'D4', name: '4. Trích lập quỹ khoa học công nghệ (nếu có)' },
    { code: 'D5', name: '5. TNTT sau khi đã trích lập quỹ KH&CN' },
    { code: 'D6', name: '6. Thuế TNDN phải nộp từ chuyển nhượng BĐS (D6 = D5 x 22%)' },
    { code: 'D7', name: '7. Thuế TNDN được miễn, giảm' },
    { code: 'D8', name: '8. Thuế TNDN phải nộp sau miễn, giảm' },
    { isHeader: true, name: 'E. TỔNG THUẾ TNDN PHẢI NỘP TRONG KỲ' },
    { code: 'E1', name: '1. Tổng số thuế TNDN phải nộp' },
    { code: 'E2', name: '2. Thuế TNDN đã tạm nộp trong năm' },
    { code: 'E3', name: '3. Thuế TNDN còn phải nộp' },
    { code: 'E4', name: '4. Thuế TNDN nộp thừa' },
    { code: 'E5', name: '5. Thuế TNDN còn phải nộp sau khi bù trừ' },
    { code: 'E6', name: '6. Thuế TNDN nộp thừa sau khi bù trừ' },
  ],
  TNCN: [
    { isHeader: true, name: 'TỔNG HỢP THUẾ THU NHẬP CÁ NHÂN' },
    { code: '15', name: 'Số hợp đồng lao động' },
    { code: '16', name: 'Tổng số người có thu nhập' },
    { code: '17', name: 'Trong đó: Số người thuộc diện phải nộp thuế' },
    { code: '18', name: 'Tổng thu nhập chịu thuế' },
    { code: '19', name: 'Tổng thu nhập tính thuế' },
    { code: '20', name: 'Tổng số thuế TNCN đã khấu trừ' },
    { code: '21', name: 'Tổng số thuế TNCN phải nộp' },
    { code: '22', name: 'Tổng số thuế TNCN đã nộp vào NSNN' },
    { code: '23', name: 'Tổng số thuế TNCN còn phải nộp' },
    { code: '24', name: 'Tổng số thuế TNCN nộp thừa' },
    { code: '25', name: 'Số người đề nghị quyết toán thay' },
    { code: '26', name: 'Số người có số thuế TNCN đề nghị hoàn trả' },
    { code: '27', name: 'Số tiền thuế TNCN đề nghị hoàn trả' },
    { code: '28', name: 'Số người có số thuế TNCN còn phải nộp' },
    { code: '29', name: 'Số thuế TNCN còn phải nộp' },
    { code: '30', name: 'Số người có số thuế TNCN bù trừ với số thuế nộp thừa' },
    { code: '31', name: 'Số thuế TNCN bù trừ với số thuế nộp thừa' },
    { code: '32', name: 'Số thuế TNCN còn phải nộp sau bù trừ' },
  ],
  // BCTC is handled by BctcTable component — UI_CONFIG entry kept for type completeness
  BCTC: [],
}

// ── BCTC (Báo cáo tài chính TT200) — separate configs per section ──────────

export const BCTC_CDKT: UiRow[] = [
  { isHeader: true, name: 'A. TÀI SẢN NGẮN HẠN' },
  { code: '100', name: 'TỔNG CỘNG TÀI SẢN NGẮN HẠN' },
  { code: '110', name: 'Tiền và các khoản tương đương tiền' },
  { code: '111', name: '  Tiền' },
  { code: '112', name: '  Các khoản tương đương tiền' },
  { code: '120', name: 'Đầu tư tài chính ngắn hạn' },
  { code: '121', name: '  Chứng khoán kinh doanh' },
  { code: '122', name: '  Dự phòng giảm giá chứng khoán kinh doanh (*)' },
  { code: '123', name: '  Đầu tư nắm giữ đến ngày đáo hạn' },
  { code: '130', name: 'Các khoản phải thu ngắn hạn' },
  { code: '131', name: '  Phải thu ngắn hạn của khách hàng' },
  { code: '132', name: '  Trả trước cho người bán ngắn hạn' },
  { code: '133', name: '  Phải thu nội bộ ngắn hạn' },
  { code: '134', name: '  Phải thu theo tiến độ kế hoạch hợp đồng xây dựng' },
  { code: '135', name: '  Phải thu về cho vay ngắn hạn' },
  { code: '136', name: '  Phải thu ngắn hạn khác' },
  { code: '137', name: '  Dự phòng phải thu ngắn hạn khó đòi (*)' },
  { code: '139', name: '  Tài sản thiếu chờ xử lý' },
  { code: '140', name: 'Hàng tồn kho' },
  { code: '141', name: '  Hàng tồn kho' },
  { code: '149', name: '  Dự phòng giảm giá hàng tồn kho (*)' },
  { code: '150', name: 'Tài sản ngắn hạn khác' },
  { code: '151', name: '  Chi phí trả trước ngắn hạn' },
  { code: '152', name: '  Thuế GTGT được khấu trừ' },
  { code: '153', name: '  Thuế và các khoản phải thu Nhà nước' },
  { code: '154', name: '  Giao dịch mua bán lại trái phiếu Chính phủ' },
  { code: '155', name: '  Tài sản ngắn hạn khác' },
  { isHeader: true, name: 'B. TÀI SẢN DÀI HẠN' },
  { code: '200', name: 'TỔNG CỘNG TÀI SẢN DÀI HẠN' },
  { code: '210', name: 'Các khoản phải thu dài hạn' },
  { code: '211', name: '  Phải thu dài hạn của khách hàng' },
  { code: '212', name: '  Trả trước cho người bán dài hạn' },
  { code: '213', name: '  Vốn kinh doanh tại các đơn vị trực thuộc' },
  { code: '214', name: '  Phải thu nội bộ dài hạn' },
  { code: '215', name: '  Phải thu về cho vay dài hạn' },
  { code: '216', name: '  Phải thu dài hạn khác' },
  { code: '219', name: '  Dự phòng phải thu dài hạn khó đòi (*)' },
  { code: '220', name: 'Tài sản cố định' },
  { code: '221', name: '  TSCĐ hữu hình — Nguyên giá' },
  { code: '222', name: '  TSCĐ hữu hình — Nguyên giá' },
  { code: '223', name: '  TSCĐ hữu hình — Giá trị hao mòn lũy kế (*)' },
  { code: '224', name: '  TSCĐ thuê tài chính — Nguyên giá' },
  { code: '225', name: '  TSCĐ thuê tài chính — Nguyên giá' },
  { code: '226', name: '  TSCĐ thuê tài chính — Giá trị hao mòn lũy kế (*)' },
  { code: '227', name: '  TSCĐ vô hình — Nguyên giá' },
  { code: '228', name: '  TSCĐ vô hình — Nguyên giá' },
  { code: '229', name: '  TSCĐ vô hình — Giá trị hao mòn lũy kế (*)' },
  { code: '230', name: 'Bất động sản đầu tư' },
  { code: '231', name: '  Nguyên giá' },
  { code: '232', name: '  Giá trị hao mòn lũy kế (*)' },
  { code: '240', name: 'Tài sản dở dang dài hạn' },
  { code: '241', name: '  Chi phí sản xuất, kinh doanh dở dang dài hạn' },
  { code: '242', name: '  Chi phí xây dựng cơ bản dở dang' },
  { code: '250', name: 'Đầu tư tài chính dài hạn' },
  { code: '251', name: '  Đầu tư vào công ty con' },
  { code: '252', name: '  Đầu tư vào công ty liên doanh, liên kết' },
  { code: '253', name: '  Đầu tư góp vốn vào đơn vị khác' },
  { code: '254', name: '  Dự phòng đầu tư tài chính dài hạn (*)' },
  { code: '255', name: '  Giao dịch mua bán lại trái phiếu Chính phủ' },
  { code: '260', name: 'Tài sản dài hạn khác' },
  { code: '261', name: '  Chi phí trả trước dài hạn' },
  { code: '262', name: '  Tài sản thuế thu nhập hoãn lại' },
  { code: '263', name: '  Thiết bị, vật tư, phụ tùng thay thế dài hạn' },
  { code: '268', name: '  Tài sản dài hạn khác' },
  { code: '270', name: 'TỔNG CỘNG TÀI SẢN' },
  { isHeader: true, name: 'C. NỢ PHẢI TRẢ' },
  { code: '300', name: 'TỔNG CỘNG NỢ PHẢI TRẢ' },
  { code: '310', name: 'Nợ ngắn hạn' },
  { code: '311', name: '  Phải trả người bán ngắn hạn' },
  { code: '312', name: '  Người mua trả tiền trước ngắn hạn' },
  { code: '313', name: '  Thuế và các khoản phải nộp Nhà nước' },
  { code: '314', name: '  Phải trả người lao động' },
  { code: '315', name: '  Chi phí phải trả ngắn hạn' },
  { code: '316', name: '  Phải trả nội bộ ngắn hạn' },
  { code: '317', name: '  Phải trả theo tiến độ kế hoạch hợp đồng xây dựng' },
  { code: '318', name: '  Doanh thu chưa thực hiện ngắn hạn' },
  { code: '319', name: '  Phải trả ngắn hạn khác' },
  { code: '320', name: '  Vay và nợ thuê tài chính ngắn hạn' },
  { code: '321', name: '  Dự phòng phải trả ngắn hạn' },
  { code: '322', name: '  Quỹ khen thưởng, phúc lợi' },
  { code: '323', name: '  Quỹ bình ổn giá' },
  { code: '324', name: '  Giao dịch mua bán lại trái phiếu Chính phủ' },
  { code: '330', name: 'Nợ dài hạn' },
  { code: '331', name: '  Phải trả người bán dài hạn' },
  { code: '332', name: '  Người mua trả tiền trước dài hạn' },
  { code: '333', name: '  Chi phí phải trả dài hạn' },
  { code: '334', name: '  Phải trả nội bộ về vốn kinh doanh' },
  { code: '335', name: '  Phải trả nội bộ dài hạn' },
  { code: '336', name: '  Doanh thu chưa thực hiện dài hạn' },
  { code: '337', name: '  Phải trả dài hạn khác' },
  { code: '338', name: '  Vay và nợ thuê tài chính dài hạn' },
  { code: '339', name: '  Trái phiếu chuyển đổi' },
  { code: '340', name: '  Cổ phiếu ưu đãi' },
  { code: '341', name: '  Thuế thu nhập hoãn lại phải trả' },
  { code: '342', name: '  Dự phòng phải trả dài hạn' },
  { code: '343', name: '  Quỹ phát triển khoa học và công nghệ' },
  { isHeader: true, name: 'D. VỐN CHỦ SỞ HỮU' },
  { code: '400', name: 'TỔNG CỘNG NGUỒN VỐN' },
  { code: '410', name: 'Vốn chủ sở hữu' },
  { code: '411', name: '  Vốn góp của chủ sở hữu' },
  { code: '411a', name: '    Cổ phiếu phổ thông có quyền biểu quyết' },
  { code: '411b', name: '    Cổ phiếu ưu đãi' },
  { code: '412', name: '  Thặng dư vốn cổ phần' },
  { code: '413', name: '  Vốn khác của chủ sở hữu' },
  { code: '414', name: '  Cổ phiếu quỹ (*)' },
  { code: '415', name: '  Chênh lệch đánh giá lại tài sản' },
  { code: '416', name: '  Chênh lệch tỷ giá hối đoái' },
  { code: '417', name: '  Quỹ đầu tư phát triển' },
  { code: '418', name: '  Quỹ hỗ trợ sắp xếp doanh nghiệp' },
  { code: '419', name: '  Quỹ khác thuộc vốn chủ sở hữu' },
  { code: '420', name: '  Lợi nhuận sau thuế chưa phân phối' },
  { code: '421', name: '    LNST chưa phân phối lũy kế đến cuối kỳ trước' },
  { code: '421a', name: '    LNST chưa phân phối lũy kế đến cuối kỳ trước (a)' },
  { code: '421b', name: '    LNST chưa phân phối lũy kế đến cuối kỳ trước (b)' },
  { code: '422', name: '    LNST chưa phân phối kỳ này' },
  { code: '430', name: '  Nguồn vốn đầu tư xây dựng cơ bản' },
  { code: '431', name: '  Quỹ khen thưởng, phúc lợi (VCSH)' },
  { code: '432', name: '  Nguồn lực tài trợ, quà biếu, tặng' },
  { code: '440', name: 'TỔNG CỘNG NGUỒN VỐN' },
]

export const BCTC_KQKD: UiRow[] = [
  { code: '01', name: 'Doanh thu bán hàng và cung cấp dịch vụ' },
  { code: '02', name: 'Các khoản giảm trừ doanh thu' },
  { code: '10', name: 'Doanh thu thuần về bán hàng và cung cấp dịch vụ (10=01-02)' },
  { code: '11', name: 'Giá vốn hàng bán' },
  { code: '20', name: 'Lợi nhuận gộp về bán hàng và cung cấp dịch vụ (20=10-11)' },
  { code: '21', name: 'Doanh thu hoạt động tài chính' },
  { code: '22', name: 'Chi phí tài chính' },
  { code: '23', name: '  Trong đó: Chi phí lãi vay' },
  { code: '25', name: 'Chi phí bán hàng' },
  { code: '26', name: 'Chi phí quản lý doanh nghiệp' },
  { code: '30', name: 'Lợi nhuận thuần từ hoạt động kinh doanh (30=20+(21-22)-(25+26))' },
  { code: '31', name: 'Thu nhập khác' },
  { code: '32', name: 'Chi phí khác' },
  { code: '40', name: 'Lợi nhuận khác (40=31-32)' },
  { code: '50', name: 'Tổng lợi nhuận kế toán trước thuế (50=30+40)' },
  { code: '51', name: 'Chi phí thuế TNDN hiện hành' },
  { code: '52', name: 'Chi phí thuế TNDN hoãn lại' },
  { code: '60', name: 'Lợi nhuận sau thuế TNDN (60=50-51-52)' },
  { code: '70', name: 'Lợi nhuận sau thuế của cổ đông thiểu số' },
  { code: '71', name: 'Lợi nhuận sau thuế của cổ đông công ty mẹ' },
]

export const BCTC_LCTT: UiRow[] = [
  { isHeader: true, name: 'I. LƯU CHUYỂN TIỀN TỪ HOẠT ĐỘNG KINH DOANH' },
  { code: '01', name: 'Tiền thu từ bán hàng, cung cấp dịch vụ và doanh thu khác' },
  { code: '02', name: 'Tiền chi trả cho người cung cấp hàng hóa và dịch vụ' },
  { code: '03', name: 'Tiền chi trả cho người lao động' },
  { code: '04', name: 'Tiền chi trả lãi vay' },
  { code: '05', name: 'Tiền chi nộp thuế thu nhập doanh nghiệp' },
  { code: '06', name: 'Tiền thu khác từ hoạt động kinh doanh' },
  { code: '07', name: 'Tiền chi khác cho hoạt động kinh doanh' },
  { code: '20', name: 'Lưu chuyển tiền thuần từ hoạt động kinh doanh' },
  { isHeader: true, name: 'II. LƯU CHUYỂN TIỀN TỪ HOẠT ĐỘNG ĐẦU TƯ' },
  { code: '21', name: 'Tiền chi mua sắm, xây dựng TSCĐ và các TSDH khác' },
  { code: '22', name: 'Tiền thu từ thanh lý, nhượng bán TSCĐ và các TSDH khác' },
  { code: '23', name: 'Tiền chi cho vay, mua công cụ nợ của đơn vị khác' },
  { code: '24', name: 'Tiền thu hồi cho vay, bán lại công cụ nợ của đơn vị khác' },
  { code: '25', name: 'Tiền chi đầu tư góp vốn vào đơn vị khác' },
  { code: '26', name: 'Tiền thu hồi đầu tư góp vốn vào đơn vị khác' },
  { code: '27', name: 'Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia' },
  { code: '30', name: 'Lưu chuyển tiền thuần từ hoạt động đầu tư' },
  { isHeader: true, name: 'III. LƯU CHUYỂN TIỀN TỪ HOẠT ĐỘNG TÀI CHÍNH' },
  { code: '31', name: 'Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu' },
  { code: '32', name: 'Tiền chi trả vốn góp cho chủ sở hữu, mua lại cổ phiếu đã phát hành' },
  { code: '33', name: 'Tiền vay ngắn hạn, dài hạn nhận được' },
  { code: '34', name: 'Tiền chi trả nợ gốc vay' },
  { code: '35', name: 'Tiền chi trả nợ gốc thuê tài chính' },
  { code: '36', name: 'Cổ tức, lợi nhuận đã trả cho chủ sở hữu' },
  { code: '40', name: 'Lưu chuyển tiền thuần từ hoạt động tài chính' },
  { code: '50', name: 'Lưu chuyển tiền thuần trong kỳ (50=20+30+40)' },
  { code: '60', name: 'Tiền và tương đương tiền đầu kỳ' },
  { code: '61', name: 'Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ' },
  { code: '70', name: 'Tiền và tương đương tiền cuối kỳ (70=50+60+61)' },
]
