import path from 'path'

export interface CrossRef {
  targetSlug: string
  label: string
  description: string
  targetAnchor?: string  // ID của điều khoản cụ thể trong tài liệu đích
}

export interface LegalDoc {
  slug: string
  title: string
  shortTitle: string
  description: string
  effectiveDate: string
  filePath: string
  theme: 'light' | 'dark'
  crossRefs: CrossRef[]
}

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: 'luat-67',
    title: 'Luật 67/2025/QH15 — Thuế Thu nhập Doanh nghiệp',
    shortTitle: 'Luật 67/2025',
    description: 'Luật Thuế TNDN mới, hiệu lực 01/10/2025. Quy định thuế suất, chi phí được trừ, ưu đãi thuế.',
    effectiveDate: '2025-10-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-67/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd320', label: 'Hướng dẫn chi tiết → Nghị định 320/2025', description: 'NĐ 320 quy định chi tiết thi hành Luật 67', targetAnchor: 'nd320_1' },
      { targetSlug: 'nd320', label: 'Điều 9 — Chi phí được trừ → NĐ 320 Điều 9–10', description: 'Chi tiết chi được trừ/không được trừ', targetAnchor: 'nd320_9' },
      { targetSlug: 'nd320', label: 'Điều 10 — Thuế suất → NĐ 320 Điều 11', description: 'Chi tiết thuế suất', targetAnchor: 'nd320_11' },
      { targetSlug: 'tt20', label: 'Thủ tục/hồ sơ → Thông tư 20/2026', description: 'TT 20 hướng dẫn hồ sơ chi được trừ, ưu đãi', targetAnchor: 'tt20_1' },
      { targetSlug: 'tt99', label: 'Điều 9 — Chi phí được trừ → hạch toán TK 642', description: 'Xem TK 642 Chi phí QLDN trong TT99', targetAnchor: 's98' },
      { targetSlug: 'tt99', label: 'Điều 10 — Thuế suất 20% → hạch toán TK 821', description: 'Xem TK 821 Chi phí thuế TNDN (TT99)', targetAnchor: 's101' },
      { targetSlug: 'tt133', label: 'Điều 10 — Thuế suất 17% SME → TK 821 TT133', description: 'DN SME: xem TK 821 trong TT133', targetAnchor: 'tt133_67' },
      { targetSlug: 'tt58', label: 'Điều 10 — Thuế suất 15% DNSN → TT58 Điều 5', description: 'DN siêu nhỏ: xem Điều 5 TT58 về phương pháp nộp thuế', targetAnchor: 'tt58_5' },
      { targetSlug: 'tt152', label: 'Điều 2, 11 — Hộ kinh doanh nộp thuế', description: 'HKD: xem phạm vi và đối tượng áp dụng TT152', targetAnchor: 'tt152_1' },
      { targetSlug: 'tt99', label: 'Điều 12–14 — Ưu đãi thuế → TK 333 TT99', description: 'Hạch toán thuế phải nộp nhà nước (TK 333)', targetAnchor: 's67' },
    ],
  },
  {
    slug: 'nd320',
    title: 'NĐ 320/2025/NĐ-CP — Hướng dẫn chi tiết Luật Thuế TNDN',
    shortTitle: 'NĐ 320/2025',
    description: 'Nghị định quy định chi tiết thi hành Luật Thuế TNDN 67/2025, hiệu lực 15/12/2025. 26 điều, 6 chương.',
    effectiveDate: '2025-12-15',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd320/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-67', label: 'Căn cứ → Luật 67/2025 (Điều 2 đối tượng)', description: 'NĐ chi tiết hóa Luật Thuế TNDN', targetAnchor: 'taxpayer' },
      { targetSlug: 'tt20', label: 'Hồ sơ/thủ tục → Thông tư 20/2026', description: 'TT 20 hướng dẫn hồ sơ chi tiết của NĐ', targetAnchor: 'tt20_1' },
      { targetSlug: 'tt99', label: 'Điều 9 — Chi phí được trừ → TK 642 (TT99)', description: 'Hạch toán chi phí QLDN', targetAnchor: 's98' },
      { targetSlug: 'tt99', label: 'Điều 11 — Thuế suất → TK 821 (TT99)', description: 'Hạch toán thuế TNDN phải nộp', targetAnchor: 's101' },
    ],
  },
  {
    slug: 'tt20',
    title: 'TT 20/2026/TT-BTC — Hướng dẫn Luật TNDN & NĐ 320/2025',
    shortTitle: 'TT 20/2026',
    description: 'Thông tư hướng dẫn hồ sơ/thủ tục theo Luật 67 và NĐ 320, hiệu lực 12/03/2026. 10 điều.',
    effectiveDate: '2026-03-12',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt20/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd320', label: 'Căn cứ → Nghị định 320/2025', description: 'TT 20 hướng dẫn chi tiết NĐ 320', targetAnchor: 'nd320_1' },
      { targetSlug: 'luat-67', label: 'Điều 3 — Hồ sơ chi được trừ → Luật Đ9', description: 'Chứng từ chi phí được trừ', targetAnchor: 'expenses' },
      { targetSlug: 'luat-67', label: 'Điều 4 — Hồ sơ ưu đãi → Luật Đ12–14', description: 'Hồ sơ hưởng ưu đãi thuế', targetAnchor: 'incentive-rates' },
      { targetSlug: 'tt99', label: 'Điều 9 — Quỹ KHCN → hạch toán (TT99)', description: 'Hạch toán Quỹ phát triển KHCN', targetAnchor: 's67' },
    ],
  },
  {
    slug: 'tt99',
    title: 'TT 99/2025/TT-BTC — Chế độ Kế toán Doanh nghiệp',
    shortTitle: 'TT 99/2025',
    description: 'Thông tư kế toán DN thay thế TT200/2014, hiệu lực 01/01/2026. Gồm hệ thống TK, biểu mẫu, sổ sách.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt99/index.html'),
    theme: 'dark',
    crossRefs: [
      { targetSlug: 'luat-67', label: 'Điều 1 TT99 → Luật thuế (Điều 2 đối tượng)', description: 'Nghĩa vụ thuế xác định theo Luật 67/2025/QH15', targetAnchor: 'taxpayer' },
      { targetSlug: 'luat-67', label: 'TK 821 → Điều 10 thuế suất TNDN', description: 'Xem Điều 10 Luật 67: thuế suất 20%/17%/15%/10%', targetAnchor: 'rates' },
      { targetSlug: 'luat-67', label: 'TK 642 → Điều 9 chi phí được trừ', description: 'Xem Điều 9 Luật 67 về điều kiện chi phí hợp lệ', targetAnchor: 'expenses' },
      { targetSlug: 'luat-67', label: 'TK 333 → Điều 12–14 ưu đãi thuế', description: 'Xem ưu đãi thuế TNDN khi hạch toán TK 333', targetAnchor: 'incentive-rates' },
      { targetSlug: 'tt133', label: 'TT99 bổ sung TT133 — xem TT133 Điều 1', description: 'DN SME chuyển từ TT133 sang TT99', targetAnchor: 'tt133_1' },
    ],
  },
  {
    slug: 'tt133',
    title: 'TT 133/2016/TT-BTC — Kế toán DN Nhỏ và Vừa',
    shortTitle: 'TT 133/2016',
    description: 'Chế độ kế toán cho DN nhỏ và vừa, hiệu lực 01/01/2017. Gồm 93 điều: hệ thống TK, BCTC, chứng từ, sổ sách.',
    effectiveDate: '2017-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt133/index.html'),
    theme: 'dark',
    crossRefs: [
      { targetSlug: 'luat-67', label: 'TK 821 → Điều 10 thuế suất 17% SME', description: 'DN nhỏ vừa (3–50 tỷ): thuế suất 17% theo Luật 67', targetAnchor: 'rates' },
      { targetSlug: 'luat-67', label: 'TK 642 → Điều 9 chi phí được trừ', description: 'Điều kiện chi phí QLDN được trừ khi tính thuế', targetAnchor: 'expenses' },
      { targetSlug: 'tt99', label: 'Tăng quy mô → chuyển sang TT99', description: 'DN vừa lớn: TT99 thay thế TT133 về kế toán', targetAnchor: 's0' },
      { targetSlug: 'tt58', label: 'DN siêu nhỏ → xem TT58 Điều 2', description: 'DNSN dưới ngưỡng SME: áp dụng TT58 thay TT133', targetAnchor: 'tt58_2' },
    ],
  },
  {
    slug: 'tt58',
    title: 'TT 58/2026/TT-BTC — Kế toán DN Siêu nhỏ',
    shortTitle: 'TT 58/2026',
    description: 'Chế độ kế toán đơn giản hóa cho DN siêu nhỏ, hiệu lực 01/07/2026. Thay thế TT132/2018.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt58/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-67', label: 'Điều 5 → Thuế suất 15% (Điều 10 Luật 67)', description: 'DNSN ≤3 tỷ: thuế suất 15% theo Luật 67', targetAnchor: 'rates' },
      { targetSlug: 'luat-67', label: 'Điều 5–6 → Tính thuế theo % DT (Điều 11)', description: 'DNSN nộp thuế % doanh thu: xem Điều 11 Luật 67', targetAnchor: 'method' },
      { targetSlug: 'tt133', label: 'Tăng quy mô → chuyển sang TT133 Điều 1', description: 'DNSN tăng lên SME: xem phạm vi TT133', targetAnchor: 'tt133_1' },
      { targetSlug: 'tt99', label: 'Vượt ngưỡng siêu nhỏ → TT99', description: 'Khi vượt tiêu chí DNSN → chuyển sang TT99', targetAnchor: 's0' },
      { targetSlug: 'tt152', label: 'HKD thành lập DNSN → Điều 1 TT58', description: 'Hộ KD thành lập DN siêu nhỏ: xem phạm vi TT58', targetAnchor: 'tt58_1' },
    ],
  },
  {
    slug: 'tt152',
    title: 'TT 152/2025/TT-BTC — Kế toán Hộ Kinh doanh',
    shortTitle: 'TT 152/2025',
    description: 'Chế độ kế toán cho hộ kinh doanh và cá nhân kinh doanh, hiệu lực 01/01/2026. Thay thế TT88/2021.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt152/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-67', label: 'Điều 1 TT152 → Điều 2 đối tượng nộp thuế', description: 'HKD trong đối tượng nộp thuế: xem Điều 2 Luật 67', targetAnchor: 'taxpayer' },
      { targetSlug: 'luat-67', label: 'Điều 4–6 → Điều 11 tính thuế theo % DT', description: 'HKD tính thuế theo % doanh thu: xem Điều 11 Luật 67', targetAnchor: 'method' },
      { targetSlug: 'tt58', label: 'HKD thành lập DN siêu nhỏ → TT58 Điều 1', description: 'Khi HKD thành lập DN: chuyển sang TT58', targetAnchor: 'tt58_1' },
      { targetSlug: 'tt133', label: 'HKD thành lập DN nhỏ vừa → TT133 Điều 1', description: 'Khi HKD thành lập DN đủ tiêu chí SME: xem TT133', targetAnchor: 'tt133_1' },
    ],
  },
  // ===== Chum thuế GTGT / TNCN / Quản lý thuế =====
  {
    slug: 'luat-48',
    title: 'Luật 48/2024/QH15 — Luật Thuế Giá trị gia tăng',
    shortTitle: 'Luật 48/2024',
    description: 'Luật Thuế GTGT, hiệu lực 01/07/2025. Đối tượng chịu/không chịu thuế, thuế suất, khấu trừ, hoàn thuế.',
    effectiveDate: '2025-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-48/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd181', label: 'Hướng dẫn chi tiết → Nghị định 181/2025', description: 'NĐ 181 quy định chi tiết thi hành Luật GTGT', targetAnchor: 'nd181_1' },
      { targetSlug: 'tt69', label: 'Hồ sơ, thủ tục → Thông tư 69/2025', description: 'TT 69 hướng dẫn hồ sơ chi tiết Luật GTGT', targetAnchor: 'tt69_1' },
      { targetSlug: 'luat-149', label: 'Sửa đổi, bổ sung → Luật 149/2025', description: 'Luật 149/2025 sửa đổi một số điều Luật GTGT', targetAnchor: 'luat-149_1' },
      { targetSlug: 'luat-67', label: 'GTGT đầu vào → Chi được trừ TNDN (Luật 67 Đ9)', description: 'Liên hệ chi phí được trừ khi tính thuế TNDN', targetAnchor: 'dieu-9' },
    ],
  },
  {
    slug: 'luat-149',
    title: 'Luật 149/2025/QH15 — Sửa đổi, bổ sung Luật Thuế GTGT',
    shortTitle: 'Luật 149/2025',
    description: 'Sửa đổi, bổ sung một số điều của Luật Thuế GTGT 48/2024.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-149/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-48', label: 'Văn bản gốc → Luật Thuế GTGT 48/2024', description: 'Luật được sửa đổi', targetAnchor: 'luat-48_1' },
    ],
  },
  {
    slug: 'luat-109',
    title: 'Luật 109/2025/QH15 — Luật Thuế Thu nhập cá nhân',
    shortTitle: 'Luật 109/2025',
    description: 'Luật Thuế TNCN (mới), hiệu lực 01/07/2026. Thu nhập chịu thuế, biểu thuế, giảm trừ, quyết toán.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-109/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-09', label: 'Sửa đổi, bổ sung → Luật 09/2026', description: 'Luật 09/2026 sửa đổi Luật TNCN', targetAnchor: 'luat-09_1' },
      { targetSlug: 'luat-108', label: 'Quản lý, kê khai, nộp thuế → Luật QLT 108/2025', description: 'Thủ tục quản lý thuế áp dụng cho TNCN', targetAnchor: 'luat-108_1' },
      { targetSlug: 'tt152', label: 'Hộ/cá nhân kinh doanh → TT 152/2025', description: 'Kế toán hộ kinh doanh nộp thuế', targetAnchor: 'tt152_1' },
    ],
  },
  {
    slug: 'luat-09',
    title: 'Luật 09/2026/QH16 — Sửa đổi Luật Thuế TNCN, GTGT',
    shortTitle: 'Luật 09/2026',
    description: 'Sửa đổi, bổ sung một số điều của Luật Thuế TNCN, Thuế GTGT và một số luật thuế khác.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-09/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-109', label: 'Văn bản gốc → Luật Thuế TNCN 109/2025', description: 'Luật được sửa đổi', targetAnchor: 'luat-109_1' },
      { targetSlug: 'luat-48', label: 'Văn bản gốc → Luật Thuế GTGT 48/2024', description: 'Luật được sửa đổi', targetAnchor: 'luat-48_1' },
    ],
  },
  {
    slug: 'luat-108',
    title: 'Luật 108/2025/QH15 — Luật Quản lý thuế',
    shortTitle: 'Luật 108/2025',
    description: 'Luật Quản lý thuế (mới), hiệu lực 01/07/2026. Đăng ký, kê khai, nộp, hoàn, thanh tra, cưỡng chế thuế.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-108/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd68', label: 'Hướng dẫn → Nghị định 68/2026', description: 'Chính sách thuế và quản lý thuế', targetAnchor: 'nd68_1' },
      { targetSlug: 'tt18', label: 'Hồ sơ, thủ tục → Thông tư 18/2026', description: 'TT 18 hướng dẫn hồ sơ, thủ tục quản lý thuế', targetAnchor: 'tt18_1' },
      { targetSlug: 'luat-38', label: 'Thay thế → Luật Quản lý thuế 38/2019', description: 'Luật QLT trước đây', targetAnchor: 'luat-38_1' },
      { targetSlug: 'luat-67', label: 'Áp dụng cho mọi sắc thuế (TNDN, GTGT, TNCN)', description: 'Quản lý thuế áp dụng chung', targetAnchor: 'dieu-1' },
    ],
  },
  {
    slug: 'luat-38',
    title: 'Luật 38/2019/QH14 — Luật Quản lý thuế',
    shortTitle: 'Luật 38/2019',
    description: 'Luật Quản lý thuế hiện hành (2019), 152 điều. Được thay thế bởi Luật 108/2025 từ 01/07/2026.',
    effectiveDate: '2020-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-38/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Được thay thế bởi → Luật QLT 108/2025', description: 'Luật QLT mới (hiệu lực 01/07/2026)', targetAnchor: 'luat-108_1' },
      { targetSlug: 'nd126', label: 'Hướng dẫn chi tiết → Nghị định 126/2020', description: 'NĐ 126 quy định chi tiết thi hành Luật QLT 2019', targetAnchor: 'nd126_1' },
      { targetSlug: 'tt80', label: 'Hồ sơ, thủ tục → Thông tư 80/2021', description: 'TT 80 hướng dẫn thi hành Luật QLT 2019', targetAnchor: 'tt80_1' },
    ],
  },
  {
    slug: 'nd181',
    title: 'NĐ 181/2025/NĐ-CP — Hướng dẫn Luật Thuế GTGT',
    shortTitle: 'NĐ 181/2025',
    description: 'Nghị định quy định chi tiết thi hành Luật Thuế GTGT 48/2024, hiệu lực 01/07/2025.',
    effectiveDate: '2025-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd181/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-48', label: 'Căn cứ → Luật Thuế GTGT 48/2024', description: 'NĐ chi tiết hóa Luật GTGT', targetAnchor: 'luat-48_1' },
      { targetSlug: 'tt69', label: 'Hồ sơ, thủ tục → Thông tư 69/2025', description: 'TT 69 hướng dẫn chi tiết NĐ 181', targetAnchor: 'tt69_1' },
      { targetSlug: 'nd273', label: 'Mẫu biểu bị thay thế → Nghị định 273/2026', description: 'NĐ 273/2026 thay biểu mẫu Phụ lục III NĐ 181 bằng Mẫu 09/BKHH Phụ lục III NĐ 273', targetAnchor: 'nd273_22' },
    ],
  },
  {
    slug: 'nd68',
    title: 'NĐ 68/2026/NĐ-CP — Chính sách thuế và quản lý thuế',
    shortTitle: 'NĐ 68/2026',
    description: 'Nghị định về chính sách thuế và quản lý thuế, hiệu lực kể từ ngày ký (05/03/2026).',
    effectiveDate: '2026-03-05',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd68/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'NĐ hướng dẫn quản lý thuế', targetAnchor: 'luat-108_1' },
      { targetSlug: 'tt18', label: 'Hồ sơ, thủ tục → Thông tư 18/2026', description: 'TT 18 hướng dẫn chi tiết', targetAnchor: 'tt18_1' },
    ],
  },
  {
    slug: 'nd144',
    title: 'NĐ 144/2026/NĐ-CP — Sửa đổi một số Nghị định về thuế',
    shortTitle: 'NĐ 144/2026',
    description: 'Sửa đổi, bổ sung một số điều của các Nghị định về thuế.',
    effectiveDate: '2026-06-20',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd144/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd181', label: 'Liên quan → Nghị định 181/2025 (GTGT)', description: 'NĐ hướng dẫn Luật GTGT', targetAnchor: 'nd181_1' },
    ],
  },
  {
    slug: 'nd359',
    title: 'NĐ 359/2025/NĐ-CP — Sửa đổi một số Nghị định về thuế',
    shortTitle: 'NĐ 359/2025',
    description: 'Sửa đổi, bổ sung một số điều của các Nghị định về thuế.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd359/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd181', label: 'Liên quan → Nghị định 181/2025 (GTGT)', description: 'NĐ hướng dẫn Luật GTGT', targetAnchor: 'nd181_1' },
    ],
  },
  {
    slug: 'tt69',
    title: 'TT 69/2025/TT-BTC — Hướng dẫn Luật Thuế GTGT',
    shortTitle: 'TT 69/2025',
    description: 'Thông tư quy định chi tiết một số điều của Luật Thuế GTGT và NĐ 181/2025, hiệu lực 01/07/2025.',
    effectiveDate: '2025-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt69/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd181', label: 'Căn cứ → Nghị định 181/2025', description: 'TT 69 hướng dẫn chi tiết NĐ 181', targetAnchor: 'nd181_1' },
      { targetSlug: 'luat-48', label: 'Căn cứ → Luật Thuế GTGT 48/2024', description: 'Hướng dẫn thi hành Luật GTGT', targetAnchor: 'luat-48_1' },
    ],
  },
  {
    slug: 'tt18',
    title: 'TT 18/2026/TT-BTC — Hồ sơ, thủ tục quản lý thuế',
    shortTitle: 'TT 18/2026',
    description: 'Thông tư quy định hồ sơ, thủ tục quản lý thuế, hiệu lực kể từ ngày ký (05/03/2026).',
    effectiveDate: '2026-03-05',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt18/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Hướng dẫn thi hành Luật QLT', targetAnchor: 'luat-108_1' },
      { targetSlug: 'nd68', label: 'Liên quan → Nghị định 68/2026', description: 'Chính sách & quản lý thuế', targetAnchor: 'nd68_1' },
    ],
  },
  // ===== Chum Thuế Tiêu thụ đặc biệt (TTĐB) =====
  {
    slug: 'luat-66',
    title: 'Luật 66/2025/QH15 — Luật Thuế Tiêu thụ đặc biệt',
    shortTitle: 'Luật 66/2025',
    description: 'Luật Thuế TTĐB, hiệu lực 01/01/2026. Đối tượng chịu thuế, giá tính thuế, thuế suất, hoàn/giảm thuế.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-66/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd360', label: 'Hướng dẫn chi tiết → Nghị định 360/2025', description: 'NĐ 360 quy định chi tiết thi hành Luật TTĐB', targetAnchor: 'nd360_1' },
      { targetSlug: 'tt158', label: 'Hồ sơ, thủ tục → Thông tư 158/2025', description: 'TT 158 hướng dẫn hồ sơ chi tiết', targetAnchor: 'tt158_1' },
      { targetSlug: 'luat-48', label: 'Hàng chịu TTĐB cũng chịu GTGT → Luật 48', description: 'Giá tính thuế GTGT gồm cả thuế TTĐB (Luật 48 Đ7)', targetAnchor: 'luat-48_7' },
      { targetSlug: 'luat-108', label: 'Kê khai, nộp, hoàn thuế → Luật QLT 108', description: 'Quản lý thuế áp dụng cho TTĐB', targetAnchor: 'luat-108_1' },
      { targetSlug: 'luat03', label: 'Thay thế Biểu thuế TTĐB sửa bởi → Luật 03/2022 Điều 8', description: 'Từ 01/01/2026, Luật 66 thay thế Biểu thuế TTĐB đã sửa tại Điều 8 Luật 03/2022', targetAnchor: 'luat03_8' },
    ],
  },
  {
    slug: 'nd360',
    title: 'NĐ 360/2025/NĐ-CP — Hướng dẫn Luật Thuế TTĐB',
    shortTitle: 'NĐ 360/2025',
    description: 'Nghị định quy định chi tiết thi hành Luật Thuế TTĐB 66/2025, hiệu lực 01/01/2026.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd360/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-66', label: 'Căn cứ → Luật Thuế TTĐB 66/2025', description: 'NĐ chi tiết hóa Luật TTĐB', targetAnchor: 'luat-66_1' },
      { targetSlug: 'tt158', label: 'Hồ sơ, thủ tục → Thông tư 158/2025', description: 'TT 158 hướng dẫn chi tiết NĐ 360', targetAnchor: 'tt158_1' },
    ],
  },
  {
    slug: 'tt158',
    title: 'TT 158/2025/TT-BTC — Hướng dẫn chi tiết NĐ 360 (TTĐB)',
    shortTitle: 'TT 158/2025',
    description: 'Thông tư quy định chi tiết một số điều của NĐ 360/2025 về thuế TTĐB, hiệu lực 01/01/2026. Có biểu mẫu hồ sơ.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt158/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd360', label: 'Căn cứ → Nghị định 360/2025', description: 'TT 158 hướng dẫn chi tiết NĐ 360', targetAnchor: 'nd360_1' },
      { targetSlug: 'luat-66', label: 'Căn cứ → Luật Thuế TTĐB 66/2025', description: 'Hướng dẫn thi hành Luật TTĐB', targetAnchor: 'luat-66_1' },
    ],
  },
  // ===== Chum Thuế Xuất nhập khẩu / Hải quan (XNK) =====
  {
    slug: 'nd134',
    title: 'NĐ 134/2016/NĐ-CP — Hướng dẫn Luật Thuế Xuất khẩu, Nhập khẩu',
    shortTitle: 'NĐ 134/2016',
    description: 'Nghị định quy định chi tiết và biện pháp thi hành Luật Thuế XNK 107/2016. Đối tượng chịu thuế, miễn/giảm/hoàn thuế XNK.',
    effectiveDate: '2016-09-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd134/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd18', label: 'Sửa đổi, bổ sung → Nghị định 18/2021', description: 'NĐ 18/2021 sửa đổi NĐ 134', targetAnchor: 'nd18_1' },
      { targetSlug: 'nd182', label: 'Sửa đổi, bổ sung → Nghị định 182/2025', description: 'NĐ 182/2025 sửa đổi NĐ 134', targetAnchor: 'nd182_1' },
      { targetSlug: 'luat-48', label: 'Thuế NK trong giá tính thuế GTGT → Luật 48 Đ7', description: 'Giá tính GTGT hàng NK gồm thuế nhập khẩu', targetAnchor: 'luat-48_7' },
      { targetSlug: 'tt85', label: 'Hướng dẫn phân loại hàng hóa → Thông tư 85/2026', description: 'TT 85/2026 hướng dẫn phân loại, phân tích hàng hóa XNK — cơ sở áp Biểu thuế XK/NK theo NĐ 134', targetAnchor: 'tt85_1' },
      { targetSlug: 'luat-108', label: 'Kê khai, nộp, hoàn thuế → Luật QLT 108', description: 'Quản lý thuế áp dụng cho thuế XNK', targetAnchor: 'luat-108_1' },
      { targetSlug: 'luat-107', label: 'Căn cứ → Luật Thuế XNK 107/2016', description: 'NĐ 134 quy định chi tiết thi hành Luật Thuế XNK 107/2016', targetAnchor: 'luat-107_1' },
    ],
  },
  {
    slug: 'nd18',
    title: 'NĐ 18/2021/NĐ-CP — Sửa đổi, bổ sung NĐ 134/2016 (Thuế XNK)',
    shortTitle: 'NĐ 18/2021',
    description: 'Sửa đổi, bổ sung một số điều của NĐ 134/2016 về thuế xuất khẩu, nhập khẩu, hiệu lực 25/04/2021.',
    effectiveDate: '2021-04-25',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd18/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd134', label: 'Văn bản gốc → Nghị định 134/2016', description: 'Nghị định được sửa đổi', targetAnchor: 'nd134_1' },
    ],
  },
  {
    slug: 'nd182',
    title: 'NĐ 182/2025/NĐ-CP — Sửa đổi, bổ sung NĐ 134/2016 (Thuế XNK)',
    shortTitle: 'NĐ 182/2025',
    description: 'Sửa đổi, bổ sung một số điều của NĐ 134/2016 về thuế xuất khẩu, nhập khẩu, hiệu lực 01/07/2025.',
    effectiveDate: '2025-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd182/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd134', label: 'Văn bản gốc → Nghị định 134/2016', description: 'Nghị định được sửa đổi', targetAnchor: 'nd134_1' },
    ],
  },
  {
    slug: 'tt06',
    title: 'TT 06/2021/TT-BTC — Hướng dẫn quản lý thuế hàng hóa XNK',
    shortTitle: 'TT 06/2021',
    description: 'Thông tư hướng dẫn thi hành về quản lý thuế đối với hàng hóa xuất khẩu, nhập khẩu, hiệu lực 08/03/2021.',
    effectiveDate: '2021-03-08',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt06/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd134', label: 'Liên quan → Nghị định 134/2016 (Thuế XNK)', description: 'Hướng dẫn quản lý thuế hàng hóa XNK', targetAnchor: 'nd134_1' },
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế', description: 'Quản lý thuế hàng hóa XNK', targetAnchor: 'luat-108_1' },
      { targetSlug: 'tt86', label: 'Kế thừa, cập nhật → Thông tư 86/2026 (cùng chủ đề, từ 01/07/2026)', description: 'TT 86/2026 quy định lại quản lý thuế hàng hóa XNK theo khung Luật Quản lý thuế 108/2025', targetAnchor: 'tt86_1' },
    ],
  },
  {
    slug: 'tt39',
    title: 'TT 39/2018/TT-BTC — Sửa đổi TT 38/2015 (thủ tục hải quan)',
    shortTitle: 'TT 39/2018',
    description: 'Sửa đổi, bổ sung TT 38/2015 về thủ tục hải quan, kiểm tra, giám sát hải quan, thuế XNK, hiệu lực 05/06/2018.',
    effectiveDate: '2018-06-05',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt39/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd134', label: 'Liên quan → Nghị định 134/2016 (Thuế XNK)', description: 'Thủ tục hải quan & thuế XNK', targetAnchor: 'nd134_1' },
      { targetSlug: 'tt86', label: 'Bị bãi bỏ một phần bởi → Thông tư 86/2026', description: 'TT 86/2026 bãi bỏ khoản 64, 65, 67, 68, 71 Điều 1 TT 39/2018', targetAnchor: 'tt86_43' },
    ],
  },
  // ===== Chum Lao động / An toàn lao động =====
  {
    slug: 'blld-45',
    title: 'BLLD 45/2019/QH14 — Bộ Luật Lao động',
    shortTitle: 'BLLD 45/2019',
    description: 'Bộ Luật Lao động 2019, hiệu lực 01/01/2021. 220 điều, 17 chương: hợp đồng lao động, tiền lương, thời giờ làm việc, ATVSLD, GQTCLĐ.',
    effectiveDate: '2021-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/blld-45/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd145', label: 'Hướng dẫn chi tiết → NĐ 145/2020', description: 'NĐ 145 hướng dẫn điều kiện LĐ và quan hệ LĐ', targetAnchor: 'nd145_1' },
      { targetSlug: 'nd293', label: 'Lương tối thiểu vùng → NĐ 293/2025', description: 'Mức lương tối thiểu áp dụng từ 01/01/2026', targetAnchor: 'nd293_1' },
      { targetSlug: 'luat-74', label: 'Việc làm → Luật 74/2025', description: 'Hỗ trợ việc làm, BHTN, đăng ký lao động', targetAnchor: 'luat-74_1' },
      { targetSlug: 'luat-41', label: 'BHXH → Luật 41/2024', description: 'Bảo hiểm xã hội bắt buộc cho người lao động', targetAnchor: 'luat-41_1' },
      { targetSlug: 'luat-25', label: 'BHYT → Luật 25/2008', description: 'Bảo hiểm y tế bắt buộc cho người lao động', targetAnchor: 'luat-25_1' },
      { targetSlug: 'luat-50', label: 'Công đoàn → Luật 50/2024', description: 'Quyền thành lập, tham gia công đoàn', targetAnchor: 'luat-50_1' },
    ],
  },
  {
    slug: 'luat-74',
    title: 'Luật 74/2025/QH15 — Luật Việc làm',
    shortTitle: 'Luật 74/2025',
    description: 'Luật Việc làm (mới), hiệu lực 01/01/2026. Chính sách hỗ trợ việc làm, BHTN, đăng ký lao động, thị trường lao động.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-74/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'blld-45', label: 'Căn cứ → Bộ Luật Lao động 45/2019', description: 'BLLD quy định về quyền làm việc', targetAnchor: 'blld-45_1' },
      { targetSlug: 'luat-41', label: 'BHTN liên kết BHXH → Luật 41/2024', description: 'Quỹ BHTN do cơ quan BHXH quản lý', targetAnchor: 'luat-41_1' },
    ],
  },
  {
    slug: 'nd145',
    title: 'NĐ 145/2020/NĐ-CP — Hướng dẫn Bộ Luật Lao động',
    shortTitle: 'NĐ 145/2020',
    description: 'Nghị định hướng dẫn thi hành BLLD 45/2019 về điều kiện lao động và quan hệ lao động, hiệu lực 01/02/2021.',
    effectiveDate: '2021-02-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd145/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'blld-45', label: 'Căn cứ → Bộ Luật Lao động 45/2019', description: 'NĐ chi tiết hóa BLLD', targetAnchor: 'blld-45_1' },
      { targetSlug: 'nd293', label: 'Tiền lương → NĐ 293/2025 lương tối thiểu', description: 'Mức lương tối thiểu vùng hiện hành', targetAnchor: 'nd293_1' },
    ],
  },
  {
    slug: 'nd293',
    title: 'NĐ 293/2025/NĐ-CP — Mức lương tối thiểu vùng',
    shortTitle: 'NĐ 293/2025',
    description: 'Quy định mức lương tối thiểu đối với người lao động làm việc theo hợp đồng lao động, hiệu lực 01/01/2026.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd293/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'blld-45', label: 'Căn cứ → Bộ Luật Lao động 45/2019', description: 'BLLD quy định về tiền lương tối thiểu', targetAnchor: 'blld-45_1' },
    ],
  },
  // ===== Chum BHXH / BHYT =====
  {
    slug: 'luat-41',
    title: 'Luật 41/2024/QH15 — Luật Bảo hiểm xã hội',
    shortTitle: 'Luật 41/2024',
    description: 'Luật BHXH (mới), hiệu lực 01/07/2025. 141 điều, 11 chương: BHXH bắt buộc, BHXH tự nguyện, BHTN, chế độ hưu trí, tử tuất.',
    effectiveDate: '2025-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-41/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'blld-45', label: 'Người lao động theo HĐLĐ → BLLD 45/2019', description: 'Phạm vi đối tượng tham gia BHXH', targetAnchor: 'blld-45_1' },
      { targetSlug: 'luat-25', label: 'BHYT song song → Luật 25/2008', description: 'Người tham gia BHXH bắt buộc đồng thời tham gia BHYT', targetAnchor: 'luat-25_1' },
      { targetSlug: 'luat-74', label: 'BHTN → Luật Việc làm 74/2025', description: 'Quỹ BHTN và chính sách BHTN', targetAnchor: 'luat-74_1' },
      { targetSlug: 'qd595', label: 'Quy trình thu BHXH → QĐ 595/BHXH', description: 'Thủ tục đăng ký, đóng BHXH, BHYT, BHTN', targetAnchor: 'qd595_1' },
    ],
  },
  {
    slug: 'luat-25',
    title: 'Luật 25/2008/QH12 — Luật Bảo hiểm y tế',
    shortTitle: 'Luật 25/2008',
    description: 'Luật Bảo hiểm y tế, hiệu lực 01/07/2009. Đối tượng tham gia, mức đóng, quyền lợi BHYT, tổ chức khám chữa bệnh.',
    effectiveDate: '2009-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-25/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-41', label: 'BHXH bắt buộc → Luật 41/2024', description: 'Người tham gia BHXH bắt buộc đồng thời tham gia BHYT', targetAnchor: 'luat-41_1' },
      { targetSlug: 'qd595', label: 'Quy trình thu BHYT → QĐ 595/BHXH', description: 'Thủ tục đăng ký, đóng BHYT', targetAnchor: 'qd595_1' },
    ],
  },
  {
    slug: 'qd595',
    title: 'QĐ 595/QĐ-BHXH — Quy trình thu BHXH, BHYT, BHTN',
    shortTitle: 'QĐ 595/BHXH',
    description: 'Ban hành Quy trình thu BHXH, BHYT, BHTN, TNLĐ-BNN, hiệu lực 01/05/2017. 54 điều, 8 chương: đăng ký tham gia, đóng, truy thu, hoàn trả.',
    effectiveDate: '2017-05-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/qd595/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-41', label: 'Căn cứ → Luật BHXH 41/2024', description: 'Quy trình thu theo Luật BHXH', targetAnchor: 'luat-41_1' },
      { targetSlug: 'luat-25', label: 'Căn cứ → Luật BHYT 25/2008', description: 'Quy trình thu BHYT', targetAnchor: 'luat-25_1' },
      { targetSlug: 'qd505', label: 'Sửa đổi, bổ sung → QĐ 505/2020', description: 'QĐ 505 sửa đổi một số điều QĐ 595', targetAnchor: 'qd505_1' },
    ],
  },
  {
    slug: 'qd505',
    title: 'QĐ 505/QĐ-BHXH — Sửa đổi Quy trình thu BHXH',
    shortTitle: 'QĐ 505/BHXH',
    description: 'Sửa đổi, bổ sung một số điều của Quy trình thu BHXH, BHYT, BHTN ban hành theo QĐ 595/2017, hiệu lực 27/03/2020.',
    effectiveDate: '2020-03-27',
    filePath: path.join(process.cwd(), 'src/legal-docs/qd505/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'qd595', label: 'Văn bản gốc → QĐ 595/QĐ-BHXH', description: 'Quy trình thu được sửa đổi', targetAnchor: 'qd595_1' },
    ],
  },
  // ===== Chum Công đoàn =====
  {
    slug: 'luat-50',
    title: 'Luật 50/2024/QH15 — Luật Công đoàn',
    shortTitle: 'Luật 50/2024',
    description: 'Luật Công đoàn, hiệu lực 01/07/2025. 37 điều, 6 chương: tổ chức, quyền, nghĩa vụ, tài chính công đoàn.',
    effectiveDate: '2025-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-50/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'blld-45', label: 'Người lao động → BLLD 45/2019', description: 'Quyền thành lập, tham gia công đoàn', targetAnchor: 'blld-45_1' },
      { targetSlug: 'nd105', label: 'Tài chính công đoàn → NĐ 105/2026', description: 'Hướng dẫn tài chính công đoàn theo Luật 50', targetAnchor: 'nd105_1' },
      { targetSlug: 'nd191', label: 'Tài chính CĐ (cũ) → NĐ 191/2013', description: 'NĐ 191 bị thay thế bởi NĐ 105/2026', targetAnchor: 'nd191_1' },
    ],
  },
  {
    slug: 'nd105',
    title: 'NĐ 105/2026/NĐ-CP — Tài chính công đoàn',
    shortTitle: 'NĐ 105/2026',
    description: 'Quy định chi tiết và hướng dẫn thi hành Luật Công đoàn về tài chính công đoàn, hiệu lực 16/05/2026.',
    effectiveDate: '2026-05-16',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd105/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-50', label: 'Căn cứ → Luật Công đoàn 50/2024', description: 'NĐ hướng dẫn tài chính công đoàn', targetAnchor: 'luat-50_1' },
      { targetSlug: 'nd191', label: 'Thay thế → NĐ 191/2013 (tài chính CĐ cũ)', description: 'NĐ 105 thay thế NĐ 191/2013', targetAnchor: 'nd191_1' },
    ],
  },
  {
    slug: 'nd191',
    title: 'NĐ 191/2013/NĐ-CP — Tài chính công đoàn (cũ)',
    shortTitle: 'NĐ 191/2013',
    description: 'Quy định chi tiết về tài chính công đoàn, hiệu lực 10/01/2014. Được thay thế bởi NĐ 105/2026 từ 16/05/2026.',
    effectiveDate: '2014-01-10',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd191/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd105', label: 'Được thay thế bởi → NĐ 105/2026', description: 'NĐ tài chính công đoàn mới (hiệu lực 16/05/2026)', targetAnchor: 'nd105_1' },
      { targetSlug: 'luat-50', label: 'Căn cứ Luật Công đoàn → Luật 50/2024', description: 'Luật CĐ mới thay thế Luật CĐ 2012', targetAnchor: 'luat-50_1' },
    ],
  },
  // ===== Chum Hóa đơn / Chứng từ =====
  {
    slug: 'nd123',
    title: 'NĐ 123/2020/NĐ-CP — Hóa đơn, chứng từ',
    shortTitle: 'NĐ 123/2020',
    description: 'Quy định về hóa đơn, chứng từ, hiệu lực 01/07/2022. Hóa đơn điện tử, hóa đơn giấy, chứng từ khấu trừ thuế TNCN.',
    effectiveDate: '2022-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd123/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd70', label: 'Sửa đổi, bổ sung → NĐ 70/2025', description: 'NĐ 70/2025 sửa đổi NĐ 123 về hóa đơn điện tử', targetAnchor: 'nd70_1' },
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Hóa đơn là cơ sở kê khai, nộp thuế', targetAnchor: 'luat-108_1' },
      { targetSlug: 'tt99', label: 'Hạch toán hóa đơn → TT 99/2025 (TK 131/331)', description: 'Hóa đơn GTGT đầu ra/đầu vào ghi nhận TK 131/331', targetAnchor: 's0' },
      { targetSlug: 'tt133', label: 'Hạch toán hóa đơn → TT 133/2016 (DN SME)', description: 'Hóa đơn trong kế toán DN nhỏ vừa', targetAnchor: 'tt133_1' },
    ],
  },
  {
    slug: 'nd70',
    title: 'NĐ 70/2025/NĐ-CP — Sửa đổi NĐ 123/2020 về hóa đơn',
    shortTitle: 'NĐ 70/2025',
    description: 'Sửa đổi, bổ sung một số điều của NĐ 123/2020 về hóa đơn, chứng từ, hiệu lực 01/06/2025.',
    effectiveDate: '2025-06-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd70/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd123', label: 'Văn bản gốc → NĐ 123/2020 (hóa đơn, chứng từ)', description: 'Nghị định được sửa đổi', targetAnchor: 'nd123_1' },
    ],
  },
  {
    slug: 'nd253',
    title: 'NĐ 253/2026/NĐ-CP — Hướng dẫn thi hành Luật Thuế TNCN',
    shortTitle: 'NĐ 253/2026',
    description: 'Quy định chi tiết và biện pháp thi hành Luật Thuế TNCN 109/2025, hiệu lực 01/07/2026. Thu nhập chịu thuế, miễn/giảm thuế, căn cứ tính thuế, khấu trừ, quyết toán, hoàn thuế.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd253/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-109', label: 'Căn cứ → Luật Thuế TNCN 109/2025', description: 'Luật gốc được NĐ 253 hướng dẫn chi tiết', targetAnchor: 'luat-109_1' },
      { targetSlug: 'luat-09', label: 'Căn cứ → Luật 09/2026 (sửa Luật TNCN)', description: 'Sửa đổi, bổ sung một số điều Luật TNCN', targetAnchor: 'luat-09_1' },
    ],
  },
  // ===== Chum Hóa đơn / Chứng từ — bổ sung =====
  {
    slug: 'nd254',
    title: 'NĐ 254/2026/NĐ-CP — Hóa đơn điện tử, chứng từ điện tử',
    shortTitle: 'NĐ 254/2026',
    description: 'Quy định chi tiết thi hành Luật Quản lý thuế 108/2025 về hóa đơn điện tử, chứng từ điện tử, hiệu lực 01/07/2026. Thay thế toàn bộ NĐ 123/2020 và NĐ 70/2025.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd254/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Luật gốc được NĐ 254 hướng dẫn chi tiết', targetAnchor: 'luat-108_1' },
      { targetSlug: 'nd123', label: 'Thay thế toàn bộ → NĐ 123/2020 (hóa đơn, chứng từ)', description: 'NĐ 123/2020 hết hiệu lực từ 01/07/2026', targetAnchor: 'nd123_1' },
      { targetSlug: 'nd70', label: 'Thay thế toàn bộ → NĐ 70/2025 (sửa NĐ 123)', description: 'NĐ 70/2025 hết hiệu lực từ 01/07/2026', targetAnchor: 'nd70_1' },
      { targetSlug: 'tt91', label: 'Hướng dẫn chi tiết → Thông tư 91/2026', description: 'TT 91/2026 quy định chi tiết hóa đơn điện tử, chứng từ điện tử theo NĐ 254', targetAnchor: 'tt91_1' },
    ],
  },
  // ===== Chum Chuyển giá / Giao dịch liên kết (TNDN) =====
  {
    slug: 'nd132',
    title: 'NĐ 132/2020/NĐ-CP — Quản lý thuế với DN có giao dịch liên kết',
    shortTitle: 'NĐ 132/2020',
    description: 'Quy định về quản lý thuế đối với doanh nghiệp có giao dịch liên kết (chuyển giá), hiệu lực 20/12/2020. Phân tích so sánh độc lập, chi phí lãi vay, hồ sơ kê khai, báo cáo lợi nhuận liên quốc gia.',
    effectiveDate: '2020-12-20',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd132/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-67', label: 'Liên quan → Luật 67/2025 (Điều 9 chi phí được trừ)', description: 'Chi phí lãi vay bên liên kết chịu khống chế theo NĐ 132', targetAnchor: 'expenses' },
      { targetSlug: 'nd320', label: 'Liên quan → NĐ 320/2025 (Điều 9–10 chi phí được trừ)', description: 'Hướng dẫn chi tiết chi phí được trừ khi tính thuế TNDN', targetAnchor: 'nd320_9' },
      { targetSlug: 'nd20', label: 'Sửa đổi, bổ sung → NĐ 20/2025', description: 'NĐ 20/2025 sửa đổi, bổ sung một số điều của NĐ 132/2020', targetAnchor: 'nd20_1' },
      { targetSlug: 'nd255', label: 'Thay thế bởi → Nghị định 255/2026 (từ 01/07/2026)', description: 'NĐ 255/2026 thay thế NĐ 132/2020, áp dụng từ kỳ tính thuế TNDN năm 2026', targetAnchor: 'nd255_1' },
    ],
  },
  {
    slug: 'nd20',
    title: 'NĐ 20/2025/NĐ-CP — Sửa đổi NĐ 132/2020 về giao dịch liên kết',
    shortTitle: 'NĐ 20/2025',
    description: 'Sửa đổi, bổ sung một số điều của NĐ 132/2020/NĐ-CP về quản lý thuế đối với doanh nghiệp có giao dịch liên kết, hiệu lực 27/03/2025.',
    effectiveDate: '2025-03-27',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd20/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd132', label: 'Văn bản gốc → NĐ 132/2020 (giao dịch liên kết)', description: 'Nghị định được sửa đổi, bổ sung', targetAnchor: 'nd132_1' },
      { targetSlug: 'nd255', label: 'Thay thế bởi → Nghị định 255/2026 (từ 01/07/2026)', description: 'NĐ 255/2026 thay thế NĐ 20/2025; Điều 3 NĐ 20 vẫn áp dụng cho đối tượng chuyển tiếp', targetAnchor: 'nd255_1' },
    ],
  },
  {
    slug: 'nd252',
    title: 'NĐ 252/2026/NĐ-CP — Hướng dẫn thi hành Luật Quản lý thuế',
    shortTitle: 'NĐ 252/2026',
    description: 'Quy định chi tiết thi hành Luật Quản lý thuế 108/2025: đăng ký thuế, khai thuế, ấn định thuế, hoàn thuế, khoanh/xóa nợ, cưỡng chế thi hành quyết định hành chính, hiệu lực 01/07/2026.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd252/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Luật gốc được NĐ 252 hướng dẫn chi tiết', targetAnchor: 'luat-108_1' },
      { targetSlug: 'nd254', label: 'Liên quan → NĐ 254/2026 (hóa đơn điện tử)', description: 'Cùng hướng dẫn Luật Quản lý thuế 108/2025, NĐ 254 phụ trách riêng phần hóa đơn/chứng từ điện tử', targetAnchor: 'nd254_1' },
      { targetSlug: 'tt90', label: 'Hướng dẫn chi tiết → Thông tư 90/2026 (đăng ký thuế)', description: 'TT 90/2026 hướng dẫn chi tiết điểm b khoản 1 Điều 40 và điểm a khoản 1 Điều 45 NĐ 252', targetAnchor: 'tt90_1' },
      { targetSlug: 'tt94', label: 'Hướng dẫn chi tiết → Thông tư 94/2026 (tuân thủ, rủi ro)', description: 'TT 94/2026 hướng dẫn quản lý tuân thủ, quản lý rủi ro trong quản lý thuế', targetAnchor: 'tt94_1' },
    ],
  },
  {
    slug: 'tt87',
    title: 'TT 87/2026/TT-BTC — Hướng dẫn thi hành Luật Thuế TNCN',
    shortTitle: 'TT 87/2026',
    description: 'Hướng dẫn chi tiết Luật Thuế TNCN 109/2025 và NĐ 253/2026/NĐ-CP, hiệu lực 01/07/2026.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt87/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd253', label: 'Căn cứ → NĐ 253/2026 (hướng dẫn chi tiết Luật Thuế TNCN)', description: 'TT 87 hướng dẫn thêm chi tiết theo NĐ 253', targetAnchor: 'nd253_1' },
      { targetSlug: 'luat-109', label: 'Căn cứ → Luật Thuế TNCN 109/2025', description: 'Luật gốc được TT 87 hướng dẫn chi tiết', targetAnchor: 'luat-109_1' },
    ],
  },
  // ===== Chum Doanh nghiệp =====
  {
    slug: 'luat-59',
    title: 'Luật 59/2020/QH14 — Luật Doanh nghiệp',
    shortTitle: 'Luật 59/2020',
    description: 'Luật Doanh nghiệp hiện hành, hiệu lực 01/01/2021. Thành lập DN, công ty TNHH, công ty cổ phần, công ty hợp danh, DNTN, DNNN, tổ chức lại/giải thể/phá sản.',
    effectiveDate: '2021-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-59/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd132', label: 'Liên quan → NĐ 132/2020 (giao dịch liên kết)', description: 'Khái niệm "người có liên quan" trong Luật DN là cơ sở xác định giao dịch liên kết', targetAnchor: 'nd132_1' },
      { targetSlug: 'luat03', label: 'Được sửa đổi bởi → Luật 03/2022 (Điều 7)', description: 'Điều 7 Luật 03/2022 sửa đổi một số điều của Luật Doanh nghiệp', targetAnchor: 'luat03_1' },
    ],
  },
  // ===== Nghị quyết độc lập — Thuế TNCN =====
  {
    slug: 'nq110',
    title: 'NQ 110/2025/UBTVQH15 — Điều chỉnh mức giảm trừ gia cảnh TNCN',
    shortTitle: 'NQ 110/2025',
    description: 'Điều chỉnh mức giảm trừ gia cảnh thuế TNCN: 15,5 triệu đồng/tháng cho người nộp thuế, 6,2 triệu đồng/tháng cho mỗi người phụ thuộc, áp dụng từ kỳ tính thuế 2026. Thay thế NQ 954/2020/UBTVQH14.',
    effectiveDate: '2026-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nq110/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-109', label: 'Căn cứ → Luật Thuế TNCN 109/2025 (Điều 19 giảm trừ gia cảnh)', description: 'NQ 110 điều chỉnh mức giảm trừ theo Điều 19 Luật TNCN', targetAnchor: 'luat-109_1' },
      { targetSlug: 'luat-09', label: 'Căn cứ → Luật 09/2026 (sửa Luật TNCN)', description: 'Sửa đổi, bổ sung một số điều Luật TNCN', targetAnchor: 'luat-09_1' },
    ],
  },
  // ===== Chum Quản lý thuế / TNDN / TNCN / TTĐB / Nhà thầu / XNK — bổ sung 2026-07 =====
  {
    slug: 'nd126',
    title: 'NĐ 126/2020/NĐ-CP — Quy định chi tiết một số điều của Luật Quản lý thuế',
    shortTitle: 'NĐ 126/2020',
    description: 'Nghị định quy định chi tiết thi hành Luật Quản lý thuế 38/2019, hiệu lực 05/12/2020. Kê khai, ấn định thuế, hoàn thuế, quản lý thuế đối với hộ/cá nhân kinh doanh, hoạt động thương mại điện tử.',
    effectiveDate: '2020-12-05',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd126/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd91', label: 'Sửa đổi, bổ sung → Nghị định 91/2022', description: 'NĐ 91/2022 sửa đổi một số điều của NĐ 126 về quản lý thuế', targetAnchor: 'nd91_1' },
      { targetSlug: 'tt80', label: 'Hướng dẫn chi tiết → Thông tư 80/2021', description: 'TT 80 hướng dẫn thi hành Luật Quản lý thuế và NĐ 126', targetAnchor: 'tt80_1' },
      { targetSlug: 'luat-38', label: 'Căn cứ → Luật Quản lý thuế 38/2019', description: 'NĐ 126 quy định chi tiết thi hành Luật Quản lý thuế 2019', targetAnchor: 'luat-38_1' },
    ],
  },
  {
    slug: 'nd91',
    title: 'NĐ 91/2022/NĐ-CP — Sửa đổi, bổ sung NĐ 126/2020 (quản lý thuế)',
    shortTitle: 'NĐ 91/2022',
    description: 'Sửa đổi, bổ sung một số điều của NĐ 126/2020/NĐ-CP quy định chi tiết một số điều của Luật Quản lý thuế, hiệu lực kể từ ngày ký ban hành (30/10/2022).',
    effectiveDate: '2022-10-30',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd91/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd126', label: 'Văn bản gốc → Nghị định 126/2020', description: 'Nghị định được sửa đổi, bổ sung', targetAnchor: 'nd126_1' },
    ],
  },
  {
    slug: 'tt80',
    title: 'TT 80/2021/TT-BTC — Hướng dẫn Luật Quản lý thuế & NĐ 126/2020',
    shortTitle: 'TT 80/2021',
    description: 'Hướng dẫn thi hành một số điều của Luật Quản lý thuế và Nghị định 126/2020/NĐ-CP, hiệu lực 01/01/2022. Hồ sơ khai thuế, ấn định thuế, hoàn thuế, quản lý thuế đối với hoạt động kinh doanh xuyên biên giới.',
    effectiveDate: '2022-01-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt80/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd126', label: 'Căn cứ → Nghị định 126/2020', description: 'TT 80 hướng dẫn thi hành NĐ 126', targetAnchor: 'nd126_1' },
      { targetSlug: 'luat-38', label: 'Căn cứ → Luật Quản lý thuế 38/2019', description: 'TT 80 hướng dẫn thi hành Luật Quản lý thuế 2019', targetAnchor: 'luat-38_1' },
      { targetSlug: 'tt103', label: 'Thuế nhà thầu → Thông tư 103/2014', description: 'Hồ sơ khai thuế áp dụng chung theo TT 80, riêng thuế nhà thầu nước ngoài xem TT 103', targetAnchor: 'tt103_1' },
      { targetSlug: 'tt21', label: 'Sửa đổi bởi → Thông tư 21/2026', description: 'TT 21/2026 sửa Điều 59, khoản 2 Điều 82, thay Mẫu 02/TNDN & 05/TNDN, bãi bỏ Điều 60', targetAnchor: 'tt21_1' },
    ],
  },
  {
    slug: 'tt103',
    title: 'TT 103/2014/TT-BTC — Thuế nhà thầu nước ngoài (FCT)',
    shortTitle: 'TT 103/2014',
    description: 'Hướng dẫn thực hiện nghĩa vụ thuế áp dụng đối với tổ chức, cá nhân nước ngoài kinh doanh tại Việt Nam hoặc có thu nhập tại Việt Nam, hiệu lực 01/10/2014. Thuế GTGT, TNDN đối với nhà thầu nước ngoài.',
    effectiveDate: '2014-10-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt103/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'tt80', label: 'Thủ tục kê khai, nộp thuế → Thông tư 80/2021', description: 'TT 80 hướng dẫn hồ sơ khai thuế áp dụng chung, gồm cả thuế nhà thầu', targetAnchor: 'tt80_1' },
    ],
  },
  {
    slug: 'luat03',
    title: 'Luật 03/2022/QH15 — Sửa đổi, bổ sung một số điều 9 luật (Đầu tư công, PPP, Đầu tư, Nhà ở, Đấu thầu, Điện lực, Doanh nghiệp, Thuế TTĐB, Thi hành án dân sự)',
    shortTitle: 'Luật 03/2022',
    description: 'Sửa đổi, bổ sung một số điều của 9 luật, hiệu lực 01/03/2022. Điều 7 sửa Luật Doanh nghiệp; Điều 8 sửa Biểu thuế Tiêu thụ đặc biệt tại Luật Thuế TTĐB.',
    effectiveDate: '2022-03-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat03/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-59', label: 'Sửa đổi → Luật Doanh nghiệp 59/2020 (Điều 7)', description: 'Điều 7 Luật 03/2022 sửa đổi một số điều của Luật Doanh nghiệp', targetAnchor: 'luat-59_1' },
      { targetSlug: 'luat-66', label: 'TTĐB → thay thế bởi Luật Thuế TTĐB 66/2025', description: 'Điều 8 sửa Biểu thuế TTĐB theo luật cũ; từ 01/01/2026 áp dụng Luật Thuế TTĐB 66/2025', targetAnchor: 'luat-66_1' },
    ],
  },
  {
    slug: 'luat-107',
    title: 'Luật 107/2016/QH13 — Luật Thuế xuất khẩu, thuế nhập khẩu',
    shortTitle: 'Luật 107/2016',
    description: 'Luật Thuế xuất khẩu, thuế nhập khẩu, hiệu lực 01/09/2016. Đối tượng chịu thuế, căn cứ tính thuế, thuế chống bán phá giá, chống trợ cấp, tự vệ, miễn/giảm/hoàn thuế XNK. Thay thế Luật Thuế XNK 45/2005.',
    effectiveDate: '2016-09-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/luat-107/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd134', label: 'Hướng dẫn chi tiết → Nghị định 134/2016', description: 'NĐ 134 quy định chi tiết và biện pháp thi hành Luật Thuế XNK 107/2016', targetAnchor: 'nd134_1' },
    ],
  },
  // ===== Đợt bổ sung 2026-07 (Tổng hợp 2) =====
  {
    slug: 'nd255',
    title: 'NĐ 255/2026/NĐ-CP — Quản lý thuế đối với Giao dịch Liên kết',
    shortTitle: 'NĐ 255/2026',
    description: 'Quy định quản lý thuế đối với giao dịch liên kết: xác định bên liên kết, phương pháp xác định giá GDLK, chi phí lãi vay ≤30% EBITDA, Hồ sơ xác định giá GDLK, Báo cáo lợi nhuận liên quốc gia. Thay thế NĐ 132/2020 và NĐ 20/2025, hiệu lực 01/07/2026, áp dụng từ kỳ tính thuế TNDN 2026.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd255/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd132', label: 'Thay thế → Nghị định 132/2020', description: 'NĐ 132/2020 hết hiệu lực kể từ ngày NĐ 255 có hiệu lực', targetAnchor: 'nd132_1' },
      { targetSlug: 'nd20', label: 'Thay thế → Nghị định 20/2025', description: 'NĐ 20/2025 hết hiệu lực; Điều 3 NĐ 20 vẫn dùng cho điều khoản chuyển tiếp', targetAnchor: 'nd20_1' },
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Quyền/nghĩa vụ NNT khi kê khai, lập Hồ sơ xác định giá GDLK theo Điều 37 Luật QLT', targetAnchor: 'luat-108_1' },
      { targetSlug: 'luat-67', label: 'Căn cứ → Luật Thuế TNDN 67/2025', description: 'Điều 16 xác định chi phí tính thuế TNDN với DN có GDLK (chi phí lãi vay, chi phí dịch vụ liên kết)', targetAnchor: 'luat-67_1' },
    ],
  },
  {
    slug: 'nd273',
    title: 'NĐ 273/2026/NĐ-CP — Kinh doanh hàng miễn thuế',
    shortTitle: 'NĐ 273/2026',
    description: 'Quy định quản lý, thủ tục, kiểm tra, giám sát hải quan đối với hoạt động kinh doanh hàng miễn thuế (cửa hàng/kho miễn thuế tại sân bay, cảng biển, cửa khẩu, bán trên tàu bay/tàu biển quốc tế). Thay thế toàn bộ NĐ 100/2020/NĐ-CP, hiệu lực 21/08/2026.',
    effectiveDate: '2026-08-21',
    filePath: path.join(process.cwd(), 'src/legal-docs/nd273/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd181', label: 'Thay thế mẫu biểu → Nghị định 181/2025', description: 'Điều 22.3 NĐ 273 thay biểu mẫu Phụ lục III NĐ 181 (hướng dẫn Luật GTGT) bằng Mẫu 09/BKHH Phụ lục III NĐ 273', targetAnchor: 'nd181_1' },
      { targetSlug: 'luat-107', label: 'Căn cứ → Luật Thuế XNK 107/2016', description: 'Căn cứ ban hành NĐ 273', targetAnchor: 'luat-107_1' },
      { targetSlug: 'luat-66', label: 'Căn cứ → Luật TTĐB 66/2025', description: 'Định lượng mua hàng miễn thuế áp dụng riêng cho rượu, thuốc lá (hàng chịu TTĐB)', targetAnchor: 'luat-66_1' },
      { targetSlug: 'luat-38', label: 'Căn cứ → Luật Quản lý thuế 38/2019', description: 'Căn cứ ban hành NĐ 273', targetAnchor: 'luat-38_1' },
    ],
  },
  {
    slug: 'tt90',
    title: 'TT 90/2026/TT-BTC — Quy định về đăng ký thuế',
    shortTitle: 'TT 90/2026',
    description: 'Hướng dẫn chi tiết đăng ký thuế theo Điều 10, 11 Luật Quản lý thuế 108/2025 và NĐ 252/2026: cấu trúc mã số thuế, thủ tục đăng ký lần đầu/thay đổi thông tin/tạm ngừng/chấm dứt/khôi phục MST cho tổ chức, hộ kinh doanh, cá nhân. Thay thế TT 86/2024/TT-BTC, hiệu lực 01/07/2026.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt90/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025 (Điều 10, 11)', description: 'TT 90 quy định chi tiết phạm vi đăng ký thuế và mã số thuế', targetAnchor: 'luat-108_1' },
      { targetSlug: 'nd252', label: 'Căn cứ → NĐ 252/2026 (Điều 40, 45)', description: 'TT 90 hướng dẫn chi tiết 2 nội dung được NĐ 252 giao', targetAnchor: 'nd252_1' },
      { targetSlug: 'tt18', label: 'Liên quan → TT 18/2026 (hồ sơ, thủ tục QLT)', description: 'Cùng nhóm thông tư hướng dẫn Luật 108/NĐ 252; TT18 phụ trách hồ sơ/thủ tục chung, TT90 phụ trách riêng đăng ký thuế', targetAnchor: 'tt18_1' },
    ],
  },
  {
    slug: 'tt21',
    title: 'TT 21/2026/TT-BTC — Sửa đổi, bổ sung một số điều của Thông tư số 80/2021/TT-BTC',
    shortTitle: 'TT 21/2026',
    description: 'Sửa đổi Điều 59 (hồ sơ miễn/giảm tiền thuê đất), khoản 2 Điều 82 (kinh phí ủy nhiệm thu) TT 80/2021; thay thế Mẫu 02/TNDN và Mẫu 05/TNDN; bãi bỏ Điều 60 TT 80/2021. Hiệu lực 17/03/2026.',
    effectiveDate: '2026-03-17',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt21/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'tt80', label: 'Sửa đổi trực tiếp → Thông tư 80/2021 (Điều 59)', description: 'TT21 sửa đổi Điều 59, khoản 2 Điều 82, thay Mẫu 02/TNDN & 05/TNDN, bãi bỏ Điều 60 của TT80/2021', targetAnchor: 'tt80_59' },
      { targetSlug: 'nd320', label: 'Điều khoản chuyển tiếp → Nghị định 320/2025', description: 'Điều 2.2 TT21 dẫn chiếu NĐ320 về DN nước ngoài chuyển nhượng vốn', targetAnchor: 'nd320_1' },
      { targetSlug: 'luat-67', label: 'Căn cứ → Luật TNDN 67/2025', description: 'Căn cứ ban hành TT21', targetAnchor: 'luat-67_1' },
    ],
  },
  {
    slug: 'tt74',
    title: 'TT 74/2026/TT-BTC — Phí, lệ phí trong lĩnh vực năng lượng nguyên tử',
    shortTitle: 'TT 74/2026',
    description: 'Quy định người nộp phí/lệ phí, tổ chức thu, mức thu, chế độ thu-nộp đối với phí thẩm định an toàn phóng xạ/bức xạ/hạt nhân, lệ phí cấp chứng chỉ nhân viên bức xạ/hành nghề dịch vụ hỗ trợ ứng dụng năng lượng nguyên tử. Thay thế TT 287/2016 và TT 116/2021, hiệu lực 10/08/2026.',
    effectiveDate: '2026-08-10',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt74/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Điều 5, Điều 6.4 dẫn chiếu Luật QLT 108/2025 cho thủ tục khai/thu/nộp NSNN', targetAnchor: 'luat-108_1' },
    ],
  },
  {
    slug: 'tt85',
    title: 'TT 85/2026/TT-BTC — Phân loại hàng hóa, phân tích để phân loại hàng hóa xuất khẩu, nhập khẩu',
    shortTitle: 'TT 85/2026',
    description: 'Quy định phân loại, phân tích để phân loại hàng hóa XNK; xây dựng, sử dụng cơ sở dữ liệu Danh mục hàng hóa XNK Việt Nam; nguyên tắc phân loại, phân loại máy liên hợp/tổ hợp máy, hồ sơ yêu cầu phân tích. Thay thế TT 14/2015 và TT 17/2021, hiệu lực 15/09/2026.',
    effectiveDate: '2026-09-15',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt85/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd134', label: 'Căn cứ → NĐ 134/2016 (Thuế XNK)', description: 'TT85 hướng dẫn phân loại hàng hóa — cơ sở áp dụng Biểu thuế XK/NK theo NĐ 134', targetAnchor: 'nd134_1' },
      { targetSlug: 'luat-107', label: 'Căn cứ → Luật Thuế XNK 107/2016', description: 'Luật gốc về thuế XNK, TT85 dẫn làm căn cứ ban hành', targetAnchor: 'luat-107_1' },
      { targetSlug: 'tt06', label: 'Liên quan → TT 06/2021 (QLT hàng XNK)', description: 'Cùng nhóm thủ tục quản lý thuế/hải quan đối với hàng hóa XNK', targetAnchor: 'tt06_1' },
    ],
  },
  {
    slug: 'tt86',
    title: 'TT 86/2026/TT-BTC — Quy định về quản lý thuế đối với hàng hóa xuất khẩu, nhập khẩu',
    shortTitle: 'TT 86/2026',
    description: 'Quy định quản lý thuế đối với hàng hóa XNK: đăng ký, khai, tính thuế; hoàn thuế; kiểm tra lại; xác nhận hoàn thành nghĩa vụ nộp thuế. Bãi bỏ một phần TT 38/2015, TT 39/2018 và TT 121/2025, hiệu lực 01/07/2026.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt86/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Thẩm quyền kiểm tra lại theo Điều 22 Luật 108/2025', targetAnchor: 'luat-108_1' },
      { targetSlug: 'luat-107', label: 'Căn cứ → Luật Thuế XNK 107/2016', description: 'Căn cứ ban hành TT86', targetAnchor: 'luat-107_1' },
      { targetSlug: 'nd134', label: 'Liên quan → Nghị định 134/2016 (Thuế XNK)', description: 'Quản lý thuế hàng hóa XNK gắn với Biểu thuế XK/NK theo NĐ 134', targetAnchor: 'nd134_1' },
      { targetSlug: 'tt06', label: 'Kế thừa, cập nhật → Thông tư 06/2021', description: 'TT86 quy định lại cùng chủ đề quản lý thuế hàng hóa XNK theo khung Luật QLT 108/2025', targetAnchor: 'tt06_1' },
      { targetSlug: 'tt39', label: 'Bãi bỏ một phần → Thông tư 39/2018', description: 'Bãi bỏ khoản 64, 65, 67, 68, 71 Điều 1 TT39/2018', targetAnchor: 'tt39_1' },
    ],
  },
  {
    slug: 'tt91',
    title: 'TT 91/2026/TT-BTC — Quy định một số điều của Luật Quản lý thuế và Nghị định số 254/2026/NĐ-CP về hóa đơn điện tử, chứng từ điện tử',
    shortTitle: 'TT 91/2026',
    description: 'Quy định chi tiết khoản 4, 7 Điều 26, khoản 3, 5 Điều 27 Luật Quản lý thuế: đăng ký sử dụng, định dạng, xử lý hóa đơn/chứng từ điện tử; ký hiệu mẫu số, ký hiệu hóa đơn; cấp hóa đơn theo từng lần phát sinh. Gồm 5 Phụ lục (I–IV bắt buộc, V tham khảo), hiệu lực 01/07/2026.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt91/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'nd254', label: 'Căn cứ → NĐ 254/2026 (hóa đơn điện tử)', description: 'TT91 quy định chi tiết Luật QLT 108/2025 và NĐ 254/2026 về hóa đơn, chứng từ điện tử', targetAnchor: 'nd254_1' },
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Điều 26, 27 Luật QLT về hóa đơn, chứng từ điện tử', targetAnchor: 'luat-108_1' },
    ],
  },
  {
    slug: 'tt94',
    title: 'TT 94/2026/TT-BTC — Quy định về quản lý tuân thủ, quản lý rủi ro trong quản lý thuế',
    shortTitle: 'TT 94/2026',
    description: 'Quy định đánh giá, phân loại mức độ tuân thủ pháp luật thuế và mức độ rủi ro của NNT; Phân hệ quản lý tuân thủ và rủi ro thuế hỗ trợ cơ quan thuế trong đăng ký thuế, kiểm tra hồ sơ khai thuế, hoàn thuế, quản lý nợ, cưỡng chế. Thay thế TT 31/2021/TT-BTC, hiệu lực 01/07/2026.',
    effectiveDate: '2026-07-01',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt94/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-108', label: 'Căn cứ → Luật Quản lý thuế 108/2025', description: 'Quản lý nợ và cưỡng chế theo Luật QLT 108/2025', targetAnchor: 'luat-108_1' },
      { targetSlug: 'nd252', label: 'Căn cứ → NĐ 252/2026', description: 'Căn cứ ban hành TT94', targetAnchor: 'nd252_1' },
      { targetSlug: 'nd254', label: 'Liên quan → NĐ 254/2026 (hóa đơn điện tử)', description: 'Phân loại rủi ro trong quản lý sử dụng hóa đơn, chứng từ', targetAnchor: 'nd254_1' },
    ],
  },
  {
    slug: 'tt96',
    title: 'TT 96/2026/TT-BTC — Sửa đổi, bổ sung một số điều của Thông tư số 67/2023/TT-BTC hướng dẫn Luật Kinh doanh bảo hiểm',
    shortTitle: 'TT 96/2026',
    description: 'Sửa đổi TT 67/2023/TT-BTC về dự phòng nghiệp vụ, tỷ lệ hoa hồng đại lý bảo hiểm theo 3 mốc thời gian, quản lý đại lý bảo hiểm cá nhân, doanh thu/chi phí doanh nghiệp bảo hiểm. Hiệu lực 02/07/2026 (riêng khoản 2 Điều 16, 17: từ 01/01/2027).',
    effectiveDate: '2026-07-02',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt96/index.html'),
    theme: 'light',
    crossRefs: [],
  },
  {
    slug: 'tt97',
    title: 'TT 97/2026/TT-BTC — Bãi bỏ Thông tư số 55/2010/TT-BTC hướng dẫn về thuế GTGT và thuế TNDN đối với Đài truyền hình',
    shortTitle: 'TT 97/2026',
    description: 'Bãi bỏ toàn bộ TT 55/2010/TT-BTC hướng dẫn thuế GTGT, TNDN riêng cho Đài truyền hình Việt Nam và các Đài truyền hình, phát thanh truyền hình tỉnh/thành phố, do khung pháp lý GTGT/TNDN đã thay đổi. Hiệu lực kể từ ngày ký (06/07/2026).',
    effectiveDate: '2026-07-06',
    filePath: path.join(process.cwd(), 'src/legal-docs/tt97/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-48', label: 'Căn cứ → Luật Thuế GTGT 48/2024', description: 'Luật GTGT hiện hành — lý do TT55/2010 (hướng dẫn GTGT cũ) không còn phù hợp và bị bãi bỏ', targetAnchor: 'luat-48_1' },
      { targetSlug: 'luat-67', label: 'Căn cứ → Luật Thuế TNDN 67/2025', description: 'Luật TNDN hiện hành — lý do TT55/2010 (hướng dẫn TNDN cũ) bị bãi bỏ', targetAnchor: 'luat-67_1' },
    ],
  },
  {
    slug: 'cv2927',
    title: 'CV 2927/CT-CS — Thuế GTGT đối với sản phẩm xuất khẩu là tài nguyên, khoáng sản',
    shortTitle: 'CV 2927/CT-CS',
    description: 'Công văn của Cục Thuế trả lời Thuế tỉnh Gia Lai về xác định thuế suất GTGT (0% hay không) đối với sản phẩm xuất khẩu là đá granite, đá thạch anh nhân tạo — tiêu chí phân biệt "tài nguyên, khoáng sản chưa chế biến" và "đã chế biến" (ngưỡng tỷ trọng giá trị tài nguyên + năng lượng ≥51% giá thành). Ban hành 11/05/2026.',
    effectiveDate: '2026-05-11',
    filePath: path.join(process.cwd(), 'src/legal-docs/cv2927/index.html'),
    theme: 'light',
    crossRefs: [
      { targetSlug: 'luat-38', label: 'Căn cứ → Luật Quản lý thuế 38/2019 (Điều 76)', description: 'CV căn cứ trực tiếp Điều 76 Luật QLT 38/2019 về thẩm quyền quyết định hoàn thuế', targetAnchor: 'luat-38_76' },
      { targetSlug: 'luat-48', label: 'Liên quan → Luật Thuế GTGT 48/2024', description: 'Luật GTGT hiện hành kế thừa quy định về sản phẩm xuất khẩu là tài nguyên/khoáng sản mà CV này giải thích theo luật cũ', targetAnchor: 'luat-48_1' },
    ],
  },
  // Thêm văn bản mới: bổ sung object và đặt file HTML vào src/legal-docs/[slug]/index.html
]

export function getDocBySlug(slug: string): LegalDoc | undefined {
  return LEGAL_DOCS.find((d) => d.slug === slug)
}
